/*
 FireShot - Webpage Screenshots and Annotations
 Copyright (C) 2007-2021 Evgeny Suslikov (evgeny@suslikov.ru)
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var e=0;return function(){return e<a.length?{done:!1,value:a[e++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var e="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return e?e.call(a):$jscomp.arrayIterator(a)};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var e=0;e<a.length;++e){var d=a[e];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,e,d){if(a==Array.prototype||a==Object.prototype)return a;a[e]=d.value;return a};$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";
var $jscomp$lookupPolyfilledValue=function(a,e){var d=$jscomp.propertyToPolyfillSymbol[e];if(null==d)return a[e];d=a[d];return void 0!==d?d:a[e]};$jscomp.polyfill=function(a,e,d,g){e&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,e,d,g):$jscomp.polyfillUnisolated(a,e,d,g))};
$jscomp.polyfillUnisolated=function(a,e,d,g){d=$jscomp.global;a=a.split(".");for(g=0;g<a.length-1;g++){var h=a[g];if(!(h in d))return;d=d[h]}a=a[a.length-1];g=d[a];e=e(g);e!=g&&null!=e&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:e})};
$jscomp.polyfillIsolated=function(a,e,d,g){var h=a.split(".");a=1===h.length;g=h[0];g=!a&&g in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<h.length-1;f++){var b=h[f];if(!(b in g))return;g=g[b]}h=h[h.length-1];d=$jscomp.IS_SYMBOL_NATIVE&&"es6"===d?g[h]:null;e=e(d);null!=e&&(a?$jscomp.defineProperty($jscomp.polyfills,h,{configurable:!0,writable:!0,value:e}):e!==d&&($jscomp.propertyToPolyfillSymbol[h]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(h):$jscomp.POLYFILL_PREFIX+h,h=
$jscomp.propertyToPolyfillSymbol[h],$jscomp.defineProperty(g,h,{configurable:!0,writable:!0,value:e})))};
$jscomp.polyfill("Promise",function(a){function e(){this.batch_=null}function d(b){return b instanceof h?b:new h(function(c,k){c(b)})}if(a&&(!($jscomp.FORCE_POLYFILL_PROMISE||$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION&&"undefined"===typeof $jscomp.global.PromiseRejectionEvent)||!$jscomp.global.Promise||-1===$jscomp.global.Promise.toString().indexOf("[native code]")))return a;e.prototype.asyncExecute=function(b){if(null==this.batch_){this.batch_=[];var c=this;this.asyncExecuteFunction(function(){c.executeBatch_()})}this.batch_.push(b)};
var g=$jscomp.global.setTimeout;e.prototype.asyncExecuteFunction=function(b){g(b,0)};e.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var b=this.batch_;this.batch_=[];for(var c=0;c<b.length;++c){var k=b[c];b[c]=null;try{k()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};e.prototype.asyncThrow_=function(b){this.asyncExecuteFunction(function(){throw b;})};var h=function(b){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];this.isRejectionHandled_=!1;var c=this.createResolveAndReject_();
try{b(c.resolve,c.reject)}catch(k){c.reject(k)}};h.prototype.createResolveAndReject_=function(){function b(l){return function(m){k||(k=!0,l.call(c,m))}}var c=this,k=!1;return{resolve:b(this.resolveTo_),reject:b(this.reject_)}};h.prototype.resolveTo_=function(b){if(b===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(b instanceof h)this.settleSameAsPromise_(b);else{a:switch(typeof b){case "object":var c=null!=b;break a;case "function":c=!0;break a;default:c=!1}c?this.resolveToNonPromiseObj_(b):
this.fulfill_(b)}};h.prototype.resolveToNonPromiseObj_=function(b){var c=void 0;try{c=b.then}catch(k){this.reject_(k);return}"function"==typeof c?this.settleSameAsThenable_(c,b):this.fulfill_(b)};h.prototype.reject_=function(b){this.settle_(2,b)};h.prototype.fulfill_=function(b){this.settle_(1,b)};h.prototype.settle_=function(b,c){if(0!=this.state_)throw Error("Cannot settle("+b+", "+c+"): Promise already settled in state"+this.state_);this.state_=b;this.result_=c;2===this.state_&&this.scheduleUnhandledRejectionCheck_();
this.executeOnSettledCallbacks_()};h.prototype.scheduleUnhandledRejectionCheck_=function(){var b=this;g(function(){if(b.notifyUnhandledRejection_()){var c=$jscomp.global.console;"undefined"!==typeof c&&c.error(b.result_)}},1)};h.prototype.notifyUnhandledRejection_=function(){if(this.isRejectionHandled_)return!1;var b=$jscomp.global.CustomEvent,c=$jscomp.global.Event,k=$jscomp.global.dispatchEvent;if("undefined"===typeof k)return!0;"function"===typeof b?b=new b("unhandledrejection",{cancelable:!0}):
"function"===typeof c?b=new c("unhandledrejection",{cancelable:!0}):(b=$jscomp.global.document.createEvent("CustomEvent"),b.initCustomEvent("unhandledrejection",!1,!0,b));b.promise=this;b.reason=this.result_;return k(b)};h.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var b=0;b<this.onSettledCallbacks_.length;++b)f.asyncExecute(this.onSettledCallbacks_[b]);this.onSettledCallbacks_=null}};var f=new e;h.prototype.settleSameAsPromise_=function(b){var c=this.createResolveAndReject_();
b.callWhenSettled_(c.resolve,c.reject)};h.prototype.settleSameAsThenable_=function(b,c){var k=this.createResolveAndReject_();try{b.call(c,k.resolve,k.reject)}catch(l){k.reject(l)}};h.prototype.then=function(b,c){function k(n,q){return"function"==typeof n?function(r){try{l(n(r))}catch(t){m(t)}}:q}var l,m,p=new h(function(n,q){l=n;m=q});this.callWhenSettled_(k(b,l),k(c,m));return p};h.prototype.catch=function(b){return this.then(void 0,b)};h.prototype.callWhenSettled_=function(b,c){function k(){switch(l.state_){case 1:b(l.result_);
break;case 2:c(l.result_);break;default:throw Error("Unexpected state: "+l.state_);}}var l=this;null==this.onSettledCallbacks_?f.asyncExecute(k):this.onSettledCallbacks_.push(k);this.isRejectionHandled_=!0};h.resolve=d;h.reject=function(b){return new h(function(c,k){k(b)})};h.race=function(b){return new h(function(c,k){for(var l=$jscomp.makeIterator(b),m=l.next();!m.done;m=l.next())d(m.value).callWhenSettled_(c,k)})};h.all=function(b){var c=$jscomp.makeIterator(b),k=c.next();return k.done?d([]):new h(function(l,
m){function p(r){return function(t){n[r]=t;q--;0==q&&l(n)}}var n=[],q=0;do n.push(void 0),q++,d(k.value).callWhenSettled_(p(n.length-1),m),k=c.next();while(!k.done)})};return h},"es6","es3");
var currentTab,currentFrameId,imgData=[],extVersion="0.0",extVersionFull="0.0",savedCapParamsForDebugging,updateURL="",pendingCapFunction,capCallbackCompleted,executeScriptTO,capId=0,processedId=0,guiItemsLocked=!1,resumeMenuEnabled=!1,shortcutProcessing=!1,commPortName="FireShot Comm Port #"+Math.ceil(45309714203*Math.random()),capResult,capLinks,multiPDFMode,canBeBetter,advFeaturesChecked=!1,tabURL,tabTitle,fPermissionsPageOpened=!1,fForcedPro=!1,fForceRegistered=!1,fSilentMode=!1,pendingResponse,
pendingGMailJSON,fInjectGmailScript=!1,fCapturing=!1,fAbortCapturing=!1,fnCancelSelection;function enableHotkey(a){a?setTimeout(function(){shortcutProcessing=!1},500):shortcutProcessing=!0}
function getVersionInfo(){""==getOption(cGUID,"")&&setOption(cGUID,getUUIDv4());var a=new XMLHttpRequest;a.open("GET",chrome.extension.getURL("manifest.json"),!0);a.onreadystatechange=function(){this.readyState==XMLHttpRequest.DONE&&(extVersion=JSON.parse(this.responseText).version.split(".",3).join("."),extVersionFull=JSON.parse(this.responseText).version.split(".",4).join("."),updateURL=JSON.parse(this.responseText).update_url,fSilentMode="hpbicldbpgipcloiojdbchegbbjiobbm"==extensionId||"adpnodbfhlagloahhdhjggicnfcpggkm"==
extensionId,isWindows()&&!isOnlyLite()?fsNativePlugin.init(function(){getConsolePtr()("Callback from fsNative");displayAnnouncements();switchToProIfRequired();updateContextMenu()}.bind(this)):displayAnnouncements())};a.send()}
function displayAnnouncements(){if("true"===getOption(cFirstTimeRun,"true"))setOption(cFirstTimeRun,!1),setOption(cCurrentVersion,extVersion),fSilentMode||openURL(getInstalledPageURL());else{var a=getOption(cCurrentVersion,"0.0");extVersion!=a&&(isNativeSupported()||fSilentMode||showBadge("https://getfireshot.com/updated-lite.php?app="+getBrowserId()+"&ver="+extVersion))}}
function getInstalledPageURL(){var a="&app="+getBrowserId();return isNativeSupported()?"https://getfireshot.com/installed.php?ver="+extVersion+a+"&native=1":"https://getfireshot.com/installed-lite.php?ver="+extVersion+a}
function nativeHostUpdated(a){getConsolePtr()("Native module has updated to the "+a+" version.");gaTrack("UA-1025658-9","fireshot.com","NativeHostUpdated");getOption(cCurrentVersion,"0.0")==extVersion||a!=extVersionFull||fSilentMode||showBadge("https://getfireshot.com/updated.php?app="+getBrowserId()+"&ver="+a+"&h="+(isProMode()?"1":"0"))}
function switchToProIfRequired(){fForcedPro=isCustomBuild()||"{5e11ab1e-083c-11e5-a6c0-1697f925ec7b}"==extensionId;fForceRegistered=isCustomBuild();setOption(cPluginProModePref,"true"===getOption(cPluginProModePref)||fForcedPro);setOption(cRegisteredPref,"true"===getOption(cRegisteredPref)||fForceRegistered)}
function pluginEvent(a){var e=a.topic,d=a.data?a.data+"":"";"status"==e?a.code==statusHostReady?pluginCommand("setAddonVersion",{version:extVersionFull,browser:extensionBrowser,id:extensionId,guid:getOption(cGUID)}):(gaTrack("UA-1025658-9","fireshot.com","NativeError-"+a.data),alert("FireShot failed to update. The updater reported the following error: \r\n-----------------------------------------------\r\n"+a.data+"\r\n-----------------------------------------------\r\n\r\nFireShot will have to work in Lite mode."),
getConsolePtr()("Error from native module: "+a.data)):"openURL"==e?openURL(d):"enableResumeMenu"==e?(getConsolePtr()("enableResumeMenu "+d),resumeMenuEnabled="enable"==d,setTimeout(function(){updateContextMenu()},10)):"setupMode"==e?(setOption(cPluginProModePref,fForcedPro||"false"!=d),updateContextMenu()):"setRegistered"==e?(setOption(cRegisteredPref,fForceRegistered||"false"!=d),updateContextMenu()):"getInfo"==e?getInfo(d,function(g){pluginCommand("processInfo",{data:g})}):"sendCrashReport"==e?
sendCrashReport(d):"base64Content"==e&&pendingResponse?pendingResponse(d):"sendToGmail"==e?openInGmail(d):"switchToLite"==e?switchToLiteMode():"getUSPTOData"==e&&doUSPTORequest(d)}function openInGmail(a){pendingGMailJSON=a;chrome.permissions.contains({origins:["https://mail.google.com/*"]},function(e){e?openGmailComposer():openGmailPermissionsPage()})}
function lockItems(){guiItemsLocked=!0;chrome.contextMenus.removeAll();chrome.browserAction.setTitle({title:"FireShot Editor is currently displayed.\r\nPlease close it to take the next capture.\r\n\r\n(switching to FireShot Pro also helps!)"});chrome.browserAction.setPopup({popup:""})}function unlockItems(){guiItemsLocked=!1;setTimeout(function(){updateContextMenu()},10);chrome.browserAction.setTitle({title:"FireShot - Capture page"});chrome.browserAction.setPopup({popup:"fsPopup.html"})}
function checkTabReadyForCapturing(a,e,d){var g=setTimeout(function(){g&&(g=void 0,d(!1))},e);chrome.tabs.executeScript(a,{code:"{}",runAt:"document_start"},function(){var h=!chrome.runtime.lastError;g&&(clearTimeout(g),g=void 0,d(h))})}
function initMessaging(){try{chrome.runtime.onMessage.addListener(function(a,e,d){switch(a.message){case "getPortName":d({portName:commPortName});break;case "loadScript":getConsolePtr()("execScript event");void 0!==executeScriptTO&&(clearTimeout(executeScriptTO),executeScriptTO=void 0);var g=e.frameId,h=["scripts/fsXBrowserSupport.js","scripts/fsUtils.js","scripts/fsSelection.js","scripts/fsLinks.js","scripts/fsContent.js"],f=0,b=function(){f<h.length?(getConsolePtr()("Executing "+h[f]),chrome.tabs.executeScript(currentTab.id,
fixObjectForOldChrome({file:h[f++],runAt:"document_start",frameId:g}),b)):setTimeout(pendingCapFunction,200)};b();break;case "execScript":getConsolePtr()("execScript event");void 0!==executeScriptTO&&(clearTimeout(executeScriptTO),executeScriptTO=void 0);setTimeout(function(){return pendingCapFunction(!1)},100);break;case "checkFSAvailabilityEvt":return getConsolePtr()("checkFSAvailabilityEvt"),d({FSAvailable:!0,FSNative:isNativeSupported(),FSUpgraded:"true"===getOption(cPluginProModePref),FSVersion:extVersionFull}),
!0;case "capturePageEvt":var c=parseInt(a.Action);c==cActionUpgrade?isNativeSupported()?doUpgrade():openURL("https://getfireshot.com/buy.php?SRC="+getBrowserId()+"-lite"):executeGrabber(c===cActionSilentSave?cActionSilentAdd:c,"true"==a.Entire?cModeEntire:cModeVisible,a.Data,function(){c===cActionSilentSave&&pluginCommand("storeEncodedContent",{path:a.Data});c!==cActionBASE64Content&&pendingResponse&&pendingResponse("")},!0,e.frameId);break;case "getScreenshotsForGmail":return pendingGMailJSON?(d(pendingGMailJSON),
pendingGMailJSON=void 0,!0):!1;case "switchToNativeEvt":installNative();break;case "activateFireShot":getConsolePtr()(a.name+" "+a.key),d("OK"),pluginCommand("activateFireShot",{name:a.name,key:a.key})}})}catch(a){}}function checkBadgeAction(){return getOption(cQueuedBadgeURLPref)&&"undefined"!==getOption(cQueuedBadgeURLPref)?(openURL(getOption(cQueuedBadgeURLPref)),showBadge(void 0),setOption(cFirstTimeRun,!1),setOption(cCurrentVersion,extVersion),!0):!1}
function checkActivationPage(a){chrome.tabs.query({currentWindow:!0,active:!0},function(e){try{if(0!==e.length&&e[0].url){var d=e[0];/https:\/\/getfireshot(\.com)?\/activate\.php/.test(d.url)&&(a(!0),chrome.tabs.executeScript(d.id,{file:"scripts/fsActivation.js",runAt:"document_start"},function(){""!==chrome.runtime.lastError&&(chrome.runtime.lastError="")}))}else a(!1)}catch(g){a(!1)}})}
function getMenuSettings(a){function e(d){var g="capturing-prohibited"===d,h="extension-page"===d,f="file-not-allowed"===d,b="capturing-executescript-disabled"===d;d=!isNativeSupported();var c="true"===getOption(cPluginProModePref),k="true"===getOption(cRegisteredPref),l=getLastMode();b={sepMain1:"visible",sepMain2:"visible",mnuFeaturesUnavailable:g?"visible":"hidden",mnuEnableFileSupport:f?"visible":"hidden",mnuPrivateBrowsingWarning:"hidden",mnuQuickLaunch:g&&(l==cModeEntire||l==cModeSelected||
l==cModeVisible)||b&&(l==cModeEntire||l==cModeSelected)?"disabled":"enabled",mnuCaptureVisible:g?"disabled":"visible",mnuCaptureEntire:g||b?"disabled":"visible",mnuCaptureSelection:g||b?"disabled":"visible",mnuCaptureVisibleLite:g?"disabled":"visible",mnuCaptureEntireLite:g||b?"disabled":"visible",mnuCaptureSelectionLite:g||b?"disabled":"visible",mnuPreferencesLite:d?"visible":"hidden",mnuViewDemo:d?"hidden":"visible",mnuSupport:d?"hidden":"visible",mnuAbout:d?"hidden":"visible",sepEditor:d?"hidden":
"visible",sepSupport1:d?"hidden":"visible",sepSupport2:d?"hidden":"visible",sepAdvanced:isWindows()?"visible":"hidden",mnuMiscellaneousFolder:d?"hidden":"visible",mnuResume:d?"hidden":resumeMenuEnabled?"enabled":"disabled",mnuUpgrade:d?"hidden":c?"hidden":"visible",mnuRegister:d?"hidden":c&&!k?"visible":"hidden",mnuEnterLicense:d?"hidden":c&&!k?"visible":"hidden",mnuOpenFile:d?"hidden":c?"enabled":"disabled",mnuOpenClipboard:d?"hidden":c?"enabled":"disabled",mnuLicenseInfo:d?"hidden":c&&k?"visible":
"hidden",divCaptureToolsLite:d?"visible":"hidden",divCaptureTools:d?"hidden":"visible",mnuFireShotNative:isWindows()&&d?"visible":"hidden",mnuStopFireShot:"hidden"};for(var m in b)fCapturing?b[m]="mnuStopFireShot"===m?"visible":"hidden":g?b[m]="mnuFeaturesUnavailable"===m?"visible":"hidden":h?"mnuPreferencesLite"===m||"mnuFireShotNative"===m&&isWindows()&&d?b[m]="visible":b[m]="hidden":f&&(b[m]="mnuEnableFileSupport"===m?"visible":"hidden");a(b)}chrome.tabs.query({currentWindow:!0,active:!0},function(d){try{if(0!==
d.length&&d[0].url){var g=d[0];/^chrome-extension.*/.test(g.url)?e("capturing-executescript-disabled"):/^safari-web-extension.*/.test(g.url)?e("extension-page"):/^file:\/\/.*/.test(g.url)?chrome.extension.isAllowedFileSchemeAccess(function(h){h?e("capturing-allowed"):e("file-not-allowed")}):/^(http|https|ftp|ftps):\/\/.*/.test(g.url)&&!/^https?:\/\/chrome.google.com\/.*$/.test(g.url)?e("capturing-allowed"):e("capturing-executescript-disabled")}else e("capturing-prohibited")}catch(h){e("capturing-prohibited")}})}
function capturePage(a,e,d,g,h,f){void 0!==executeScriptTO&&(clearTimeout(executeScriptTO),executeScriptTO=void 0);capId++;currentTab=h;currentFrameId=f;capCallbackCompleted=g;pendingCapFunction=function(b){b?captureVisibleTabPlain(a,d,g):doCapturing(a,e,d,g)};getConsolePtr()("capturePage: checking capabilities at "+h.url+". Tab state is: "+h.status);e==cModeBrowser&&void 0!==h.url&&void 0!==h.title?setTimeout(function(){getConsolePtr()("Calling captureBrowser directly...");enableHotkey(!1);lockItems();
pluginCommand("captureBrowser",{action:a+":-",url:h.url,title:h.title});unlockItems();enableHotkey(!0);capCallbackCompleted&&capCallbackCompleted()},100):(executeScriptTO=setTimeout(function(){getConsolePtr()("Calling doCapturing on timeout");pendingCapFunction(!0)},1E3),chrome.tabs.executeScript(h.id,fixObjectForOldChrome({file:"scripts/fsScriptChecker.js",runAt:"document_start",frameId:f}),function(){chrome.runtime.lastError&&(clearTimeout(executeScriptTO),executeScriptTO=void 0,getConsolePtr()("Calling doCapturing on lastError"),
pendingCapFunction(!0))}))}function getActionLocaleId(a){switch(a){case cActionSave:return"action_save";case cActionSavePDF:return"action_save_pdf";case cActionClipboard:return"action_copy";case cActionEMail:return"action_email";case cActionPaint:return"action_external";case cActionSendOneNote:return"action_onenote";case cActionUpload:return"action_upload";case cActionPrint:return"action_print";case cActionMultiPDF:return"action_save_pdf_single";default:return"action_edit"}}
function getLADescription(){var a=getActionLocaleId(getLastAction()),e=!isNativeSupported();switch(getLastMode()){case cModeVisible:var d=e?"action_capture_visible_lite":"action_capture_visible";break;case cModeSelected:d=e?"action_capture_selection_lite":"action_capture_selection";break;case cModeBrowser:d="action_capture_browser";break;case cModeTabs:d="action_capture_tabs";break;default:d=e?"action_capture_entire_lite":"action_capture_entire"}return e?chrome.i18n.getMessage(d):chrome.i18n.getMessage(d)+
" "+chrome.i18n.getMessage(a)}function stopCapturing(){fAbortCapturing=!0;getConsolePtr()("Capturing canceled");fnCancelSelection&&fnCancelSelection()}
function captureVisibleTabPlain(a,e,d){var g=function(h){chrome.tabs.captureVisibleTab(void 0,{format:"png"},function(f){if(!chrome.runtime.lastError&&f){var b=new Image;b.onload=function(){pluginCommand("captureInit");pluginCommand("captureTabPNG",{dataurl:f,datasize:f.length,x:0,y:0});tabURL=currentTab.url;tabTitle=currentTab.title;var c={action:a,url:tabURL,title:tabTitle,left:0,top:0,width:b.width,height:b.height};c.browserVersion=parseInt(navigator.userAgent.match(/(Chrom(e|ium)|Safari)\/([0-9]+)\./)[3]);
c.usrData=e;pendingResponse=function(k){pendingResponse=void 0;port.postMessage({topic:"sendFireShotCaptureCompleteEvent",data:k})};lockItems();pluginCommand("captureDone",c);enableHotkey(!0);unlockItems();d&&d(!0)};b.src=f}else 5>h?(getConsolePtr()("retry "+h),setTimeout(function(){g(++h)},50)):(getConsolePtr()("Maximum attempts to call captureVisibleTab reached"),lockItems(),enableHotkey(!0),unlockItems(),d&&d(!0))})};g(0)}
function doCapturing(a,e,d,g){function h(c){chrome.tabs.captureVisibleTab(currentTab.windowId,{format:"jpeg"},function(k){var l=-1,m=-1;if(chrome.runtime.lastError)console.error(chrome.runtime.lastError.message);else try{var p=getJpegExtents(k);l=p[0];m=p[1];getConsolePtr()("Emulation extents: "+p[0]+" x "+p[1])}catch(n){getConsolePtr()(n.toString())}c(l,m)})}fAbortCapturing=!1;getConsolePtr()("doCapturing");if(capId<=processedId++)capId=processedId;else try{var f=chrome.tabs.connect(currentTab.id,
{name:commPortName,frameId:currentFrameId}),b=function(){fCapturing=!1;updateContextMenu();g&&g(!1)};f.onMessage.addListener(function(c){getConsolePtr()(JSON.stringify(c));switch(c.topic){case "initAborted":getConsolePtr()("init Aborted");fCapturing=!1;updateContextMenu();g&&g();break;case "initDone":tabURL=c.url;tabTitle=c.title;connecting=!1;enableHotkey(!1);switch(e){case cModeVisible:case cModeEntire:h(function(l,m){l=closestToInt(l/c.cw);m=closestToInt(m/c.ch);pluginCommand("captureInit");f.postMessage({topic:"setRatio",
ratioW:l,ratioH:m});f.postMessage({topic:"scrollNext"})});break;case cModeSelected:h(function(l,m){l=closestToInt(l/c.cw);m=closestToInt(m/c.ch);pluginCommand("captureInit");fnCancelSelection=function(){f.postMessage({topic:"cancelSelection"})};f.postMessage({topic:"setRatio",ratioW:l,ratioH:m});f.postMessage({topic:"selectArea"})});break;case cModeBrowser:enableHotkey(!1),lockItems(),pluginCommand("captureBrowser",{action:a+":-",url:tabURL,title:tabTitle}),unlockItems(),enableHotkey(!0)}break;case "areaSelected":fnCancelSelection=
void 0;f.postMessage({topic:"scrollNext"});break;case "areaSelectionCanceled":fnCancelSelection=void 0;fCapturing=!1;updateContextMenu();enableHotkey(!0);f.onMessage.removeListener(arguments.callee);f.onDisconnect.removeListener(b);break;case "scrollDone":var k=function(l){chrome.tabs.captureVisibleTab(currentTab.windowId,{format:"png"},function(m){!chrome.runtime.lastError&&m?(pluginCommand("captureTabPNG",{dataurl:m,datasize:m.length,x:c.x,y:c.y}),f.postMessage({topic:"scrollNext",cancel:fAbortCapturing})):
40>l?(getConsolePtr()("retry "+l),setTimeout(function(){k(++l)},50)):(getConsolePtr()("Maximum attempts to call captureVisibleTab reached"),f.postMessage({topic:"scrollNext",cancel:!0}))})};k(0);break;case "scrollFinished":getConsolePtr()("FINISHED ("+c.rows+" x "+c.cols+")");fCapturing=!1;f.onMessage.removeListener(arguments.callee);f.onDisconnect.removeListener(b);savedCapParamsForDebugging={action:c.action,left:c.left,top:c.top,width:c.width,height:c.height,rows:c.rows,cols:c.cols,cw:c.cw,ch:c.ch,
ratioW:c.ratioW,ratioH:c.ratioH,cropLeft:c.cropLeft,cropRight:c.cropRight,cropTop:c.cropTop,cropBottom:c.cropBottom};c.url=tabURL;c.title=tabTitle;c.key="-";c.action=a;c.browserVersion=parseInt(navigator.userAgent.match(/(Chrom(e|ium)|Safari)\/([0-9]+)\./)[3]);c.usrData=d;pendingResponse=function(l){pendingResponse=void 0;f.postMessage({topic:"sendFireShotCaptureCompleteEvent",data:l})};lockItems();pluginCommand("captureDone",c);enableHotkey(!0);unlockItems();g&&g(!0);break;case "setOption":setOption(c.optionName,
c.optionValue)}});f.onDisconnect.addListener(b);fCapturing=!0;updateContextMenu();f.postMessage({topic:"init",mode:e,debug:isDebug,options:JSON.stringify(localStorage),p:"true"===getOption(cPluginProModePref),native:isNativeSupported(),frameMode:0<currentFrameId})}catch(c){fCapturing=!1,g&&g(!1)}}
function genericOnClick(a,e){switch(a.menuItemId){case mnuTest:doTest();break;case mnuStopFireShot:stopCapturing();break;case mnuVisibleEdit:executeGrabber(cActionEdit,cModeVisible);break;case mnuVisibleSave:executeGrabber(cActionSave,cModeVisible);break;case mnuVisibleSavePDF:executeGrabber(cActionSavePDF,cModeVisible);break;case mnuVisibleSendOneNote:executeGrabber(cActionSendOneNote,cModeVisible);break;case mnuVisibleUpload:executeGrabber(cActionUpload,cModeVisible);break;case mnuVisiblePrint:executeGrabber(cActionPrint,
cModeVisible);break;case mnuVisibleCopy:executeGrabber(cActionClipboard,cModeVisible);break;case mnuVisibleEMail:executeGrabber(cActionEMail,cModeVisible);break;case mnuVisibleExtEditor:executeGrabber(cActionPaint,cModeVisible);break;case mnuEntireEdit:executeGrabber(cActionEdit,cModeEntire);break;case mnuEntireSave:executeGrabber(cActionSave,cModeEntire);break;case mnuEntireSavePDF:executeGrabber(cActionSavePDF,cModeEntire);break;case mnuEntireSendOneNote:executeGrabber(cActionSendOneNote,cModeEntire);
break;case mnuEntireUpload:executeGrabber(cActionUpload,cModeEntire);break;case mnuEntirePrint:executeGrabber(cActionPrint,cModeEntire);break;case mnuEntireCopy:executeGrabber(cActionClipboard,cModeEntire);break;case mnuEntireEMail:executeGrabber(cActionEMail,cModeEntire);break;case mnuEntireExtEditor:executeGrabber(cActionPaint,cModeEntire);break;case mnuSelectedEdit:executeGrabber(cActionEdit,cModeSelected);break;case mnuSelectedSave:executeGrabber(cActionSave,cModeSelected);break;case mnuSelectedSavePDF:executeGrabber(cActionSavePDF,
cModeSelected);break;case mnuSelectedSendOneNote:executeGrabber(cActionSendOneNote,cModeSelected);break;case mnuSelectedUpload:executeGrabber(cActionUpload,cModeSelected);break;case mnuSelectedPrint:executeGrabber(cActionPrint,cModeSelected);break;case mnuSelectedCopy:executeGrabber(cActionClipboard,cModeSelected);break;case mnuSelectedEMail:executeGrabber(cActionEMail,cModeSelected);break;case mnuSelectedExtEditor:executeGrabber(cActionPaint,cModeSelected);break;case mnuBrowserEdit:executeGrabber(cActionEdit,
cModeBrowser);break;case mnuBrowserSave:executeGrabber(cActionSave,cModeBrowser);break;case mnuBrowserSavePDF:executeGrabber(cActionSavePDF,cModeBrowser);break;case mnuBrowserSendOneNote:executeGrabber(cActionSendOneNote,cModeBrowser);break;case mnuBrowserUpload:executeGrabber(cActionUpload,cModeBrowser);break;case mnuBrowserPrint:executeGrabber(cActionPrint,cModeBrowser);break;case mnuBrowserCopy:executeGrabber(cActionClipboard,cModeBrowser);break;case mnuBrowserEMail:executeGrabber(cActionEMail,
cModeBrowser);break;case mnuBrowserExtEditor:executeGrabber(cActionPaint,cModeBrowser);break;case mnuAllTabsEdit:tabsPermissionRequired(function(){executeGrabber(cActionEdit,cModeTabs)});break;case mnuAllTabsSinglePDF:tabsPermissionRequired(function(){executeGrabber(cActionMultiPDF,cModeTabs)});break;case mnuAllTabsSave:tabsPermissionRequired(function(){executeGrabber(cActionSave,cModeTabs)});break;case mnuAllTabsSendOneNote:tabsPermissionRequired(function(){executeGrabber(cActionSendOneNote,cModeTabs)});
break;case mnuAllTabsUpload:tabsPermissionRequired(function(){executeGrabber(cActionUpload,cModeTabs)});break;case mnuAllTabsPrint:tabsPermissionRequired(function(){executeGrabber(cActionPrint,cModeTabs)});break;case mnuAllTabsClipboard:tabsPermissionRequired(function(){executeGrabber(cActionClipboard,cModeTabs)});break;case mnuAllTabsEMail:tabsPermissionRequired(function(){executeGrabber(cActionEMail,cModeTabs)});break;case mnuAllTabsExtEditor:tabsPermissionRequired(function(){executeGrabber(cActionPaint,
cModeTabs)});break;case mnuLastAction:captureLastUsedMode();break;case mnuPreferences:openExtensionPreferences();break;case mnuViewDemo:openDemoPage();break;case mnuSupport:openSupportPage();break;case mnuAPI:openAPIPage();break;case mnuUnlockProFeatures:case mnuUpgrade:doUpgrade();break;case mnuRegister:doRegister();break;case mnuEnterLicense:enterLicense();break;case mnuOpenFile:openFile();break;case mnuOpenClipboard:openClipboard();break;case mnuResume:resumeEditing();break;case mnuFireShotNative:installNative();
break;case mnuLicensingInfo:showLicenseInfo();break;case mnuAbout:showAbout()}}function updateLastActionInContextMenu(){chrome.commands.getAll(function(a){getLAShortcut(function(e){chrome.contextMenus.update(mnuLastAction,{onclick:genericOnClick,title:getLADescription()+"    "+e},function(){""!==chrome.runtime.lastError&&(chrome.runtime.lastError="")})})})}
var fEntered=!1,mnuStopFireShot,mnuLastAction,mnuVisibleEdit,mnuVisibleSave,mnuVisibleSavePDF,mnuVisibleSendOneNote,mnuVisibleUpload,mnuVisiblePrint,mnuVisibleCopy,mnuVisibleEMail,mnuVisibleExtEditor,mnuEntireEdit,mnuEntireSave,mnuEntireSavePDF,mnuEntireSendOneNote,mnuEntireUpload,mnuEntirePrint,mnuEntireCopy,mnuEntireEMail,mnuEntireExtEditor,mnuSelectedEdit,mnuSelectedSave,mnuSelectedSavePDF,mnuSelectedSendOneNote,mnuSelectedUpload,mnuSelectedPrint,mnuSelectedCopy,mnuSelectedEMail,mnuSelectedExtEditor,
mnuBrowserEdit,mnuBrowserSave,mnuBrowserSavePDF,mnuBrowserSendOneNote,mnuBrowserUpload,mnuBrowserPrint,mnuBrowserCopy,mnuBrowserEMail,mnuBrowserExtEditor,mnuResume,mnuOpenFile,mnuOpenClipboard,mnuPreferences,mnuRegister,mnuEnterLicense,mnuUpgrade,mnuViewDemo,mnuSupport,mnuAPI,mnuLicensingInfo,mnuAbout,mnuFireShotNative,mnuTest,mnuAllTabsEdit,mnuAllTabsSinglePDF,mnuUnlockProFeatures,mnuAllTabsSave,mnuAllTabsSendOneNote,mnuAllTabsUpload,mnuAllTabsPrint,mnuAllTabsEMail,mnuAllTabsExtEditor,mnuAllTabsClipboard;
function updateContextMenu(){fEntered||(fEntered=!0,chrome.contextMenus.removeAll(function(){function a(){chrome.contextMenus.create({onclick:function(){},type:"separator",documentUrlPatterns:h})}if("true"!==getOption(cContextMenuIntegrationPref,"true"))fEntered=!1;else{var e="true"===getOption(cPluginProModePref),d="true"===getOption(cRegisteredPref),g=!isNativeSupported(),h=["http://*/*","https://*/*","ftp://*/*","file://*/*"];if(fCapturing)mnuStopFireShot=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_capture_stop"),
onclick:genericOnClick}),fEntered=!1;else if(!guiItemsLocked){isDebug&&(mnuTest=chrome.contextMenus.create({title:"do test",onclick:genericOnClick}),a());mnuLastAction=chrome.contextMenus.create({title:"Last action",onclick:genericOnClick,documentUrlPatterns:h});if(!isSafari()){a();if(g)mnuEntireEdit=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_capture_entire_lite")+"...",onclick:genericOnClick,documentUrlPatterns:h}),mnuVisibleEdit=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_capture_visible_lite")+
"...",onclick:genericOnClick,documentUrlPatterns:h}),mnuSelectedEdit=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_capture_selection_lite")+"...",onclick:genericOnClick,documentUrlPatterns:h}),a();else{var f=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_capture_visible")+"..."});mnuVisibleEdit=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_edit")+"...",parentId:f,onclick:genericOnClick});mnuVisibleSave=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_save")+
"...",parentId:f,onclick:genericOnClick});mnuVisibleSavePDF=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_save_pdf")+"...",parentId:f,onclick:genericOnClick});mnuVisibleSendOneNote=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_onenote")+"...",parentId:f,onclick:genericOnClick});mnuVisibleUpload=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_upload")+"...",parentId:f,onclick:genericOnClick});mnuVisiblePrint=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_print")+
"...",parentId:f,onclick:genericOnClick});mnuVisibleCopy=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_copy")+"...",parentId:f,onclick:genericOnClick});mnuVisibleEMail=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_email")+"...",parentId:f,onclick:genericOnClick});mnuVisibleExtEditor=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_external")+"...",parentId:f,onclick:genericOnClick});f=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_capture_entire")+
"..."});mnuEntireEdit=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_edit")+"...",parentId:f,onclick:genericOnClick});mnuEntireSave=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_save")+"...",parentId:f,onclick:genericOnClick});mnuEntireSavePDF=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_save_pdf")+"...",parentId:f,onclick:genericOnClick});mnuEntireSendOneNote=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_onenote")+"...",
parentId:f,onclick:genericOnClick});mnuEntireUpload=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_upload")+"...",parentId:f,onclick:genericOnClick});mnuEntirePrint=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_print")+"...",parentId:f,onclick:genericOnClick});mnuEntireCopy=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_copy")+"...",parentId:f,onclick:genericOnClick});mnuEntireEMail=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_email")+
"...",parentId:f,onclick:genericOnClick});mnuEntireExtEditor=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_external")+"...",parentId:f,onclick:genericOnClick});f=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_capture_selection")+"..."});mnuSelectedEdit=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_edit")+"...",parentId:f,onclick:genericOnClick});mnuSelectedSave=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_save")+"...",parentId:f,
onclick:genericOnClick});mnuSelectedSavePDF=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_save_pdf")+"...",parentId:f,onclick:genericOnClick});mnuSelectedSendOneNote=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_onenote")+"...",parentId:f,onclick:genericOnClick});mnuSelectedUpload=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_upload")+"...",parentId:f,onclick:genericOnClick});mnuSelectedPrint=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_print")+
"...",parentId:f,onclick:genericOnClick});mnuSelectedCopy=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_copy")+"...",parentId:f,onclick:genericOnClick});mnuSelectedEMail=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_email")+"...",parentId:f,onclick:genericOnClick});mnuSelectedExtEditor=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_external")+"...",parentId:f,onclick:genericOnClick});f=g||chrome.contextMenus.create({title:chrome.i18n.getMessage("action_capture_browser")+
"..."});mnuBrowserEdit=g||chrome.contextMenus.create({title:chrome.i18n.getMessage("action_edit")+"...",parentId:f,onclick:genericOnClick});mnuBrowserSave=g||chrome.contextMenus.create({title:chrome.i18n.getMessage("action_save")+"...",parentId:f,onclick:genericOnClick});mnuBrowserSavePDF=g||chrome.contextMenus.create({title:chrome.i18n.getMessage("action_save_pdf")+"...",parentId:f,onclick:genericOnClick});mnuBrowserSendOneNote=g||chrome.contextMenus.create({title:chrome.i18n.getMessage("action_onenote")+
"...",parentId:f,onclick:genericOnClick});mnuBrowserUpload=g||chrome.contextMenus.create({title:chrome.i18n.getMessage("action_upload")+"...",parentId:f,onclick:genericOnClick});mnuBrowserPrint=g||chrome.contextMenus.create({title:chrome.i18n.getMessage("action_print")+"...",parentId:f,onclick:genericOnClick});mnuBrowserCopy=g||chrome.contextMenus.create({title:chrome.i18n.getMessage("action_copy")+"...",parentId:f,onclick:genericOnClick});mnuBrowserEMail=g||chrome.contextMenus.create({title:chrome.i18n.getMessage("action_email")+
"...",parentId:f,onclick:genericOnClick});mnuBrowserExtEditor=g||chrome.contextMenus.create({title:chrome.i18n.getMessage("action_external")+"...",parentId:f,onclick:genericOnClick});f=g||chrome.contextMenus.create({title:chrome.i18n.getMessage("action_capture_tabs")+"..."});mnuUnlockProFeatures=e||g||chrome.contextMenus.create({title:chrome.i18n.getMessage("action_switch_pro_tabs"),parentId:f,onclick:genericOnClick});mnuAllTabsSinglePDF=g||chrome.contextMenus.create({enabled:e,title:chrome.i18n.getMessage("action_save_pdf_single")+
"...",parentId:f,onclick:genericOnClick});mnuAllTabsEdit=g||chrome.contextMenus.create({enabled:e,title:chrome.i18n.getMessage("action_edit")+"...",parentId:f,onclick:genericOnClick});mnuAllTabsSave=g||chrome.contextMenus.create({enabled:e,title:chrome.i18n.getMessage("action_save")+"...",parentId:f,onclick:genericOnClick});mnuAllTabsSendOneNote=g||chrome.contextMenus.create({enabled:e,title:chrome.i18n.getMessage("action_onenote")+"...",parentId:f,onclick:genericOnClick});mnuAllTabsUpload=g||chrome.contextMenus.create({enabled:e,
title:chrome.i18n.getMessage("action_upload")+"...",parentId:f,onclick:genericOnClick});mnuAllTabsPrint=g||chrome.contextMenus.create({enabled:e,title:chrome.i18n.getMessage("action_print")+"...",parentId:f,onclick:genericOnClick});mnuAllTabsClipboard=g||chrome.contextMenus.create({enabled:e,title:chrome.i18n.getMessage("action_copy")+"...",parentId:f,onclick:genericOnClick});mnuAllTabsEMail=g||chrome.contextMenus.create({enabled:e,title:chrome.i18n.getMessage("action_email")+"...",parentId:f,onclick:genericOnClick});
mnuAllTabsExtEditor=g||chrome.contextMenus.create({enabled:e,title:chrome.i18n.getMessage("action_external")+"...",parentId:f,onclick:genericOnClick});a();!g&&e&&(resumeMenuEnabled&&(mnuResume=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_resume")+"...",onclick:genericOnClick})),mnuOpenFile=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_open_file")+"...",onclick:genericOnClick}),mnuOpenClipboard=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_open_clipboard")+
"...",onclick:genericOnClick}),a());mnuPreferences=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_options")+"...",onclick:genericOnClick});mnuFireShotNative=!isWindows()||!g||chrome.contextMenus.create({title:chrome.i18n.getMessage("action_install_native")+"...",parentId:f,onclick:genericOnClick});g||a()}g||!e||d||(mnuRegister=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_register")+"...",onclick:genericOnClick}),mnuEnterLicense=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_enter_license")+
"...",onclick:genericOnClick}));g||e||(mnuUpgrade=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_switch_pro")+"!",onclick:genericOnClick}));mnuViewDemo=g||chrome.contextMenus.create({title:chrome.i18n.getMessage("action_view_demo"),onclick:genericOnClick});mnuSupport=g||chrome.contextMenus.create({title:chrome.i18n.getMessage("action_support"),onclick:genericOnClick});!g&&e&&d&&(mnuLicensingInfo=chrome.contextMenus.create({title:chrome.i18n.getMessage("action_license_info"),onclick:genericOnClick}));
mnuAbout=g||chrome.contextMenus.create({title:chrome.i18n.getMessage("action_about"),onclick:genericOnClick})}updateLastActionInContextMenu();fEntered=!1}}}))}function restoreBadge(){getOption(cQueuedBadgeURLPref)&&"undefined"!==getOption(cQueuedBadgeURLPref)&&showBadge(getOption(cQueuedBadgeURLPref))}
function executeGrabber(a,e,d,g,h,f){f=f||0;guiItemsLocked||(h||setLastActionAndMode(a,e),e===cModeTabs?captureTabs(a):(multiPDFMode&&(pluginCommand("cancelMultiPagePDF"),multiPDFMode=void 0),chrome.tabs.query({currentWindow:!0,active:!0},function(b){0<b.length&&capturePage(a,e,d,g,b[0],f)})))}
function captureTabs(a){function e(f,b){return{next:function(c){b(c)||f(this)}}}var d=new function(){return{running:!1,start:function(){var f=0,b=["images/progress_1.png","images/progress_2.png","images/progress_3.png","images/progress_4.png"],c=this,k=function(){c.running?(chrome.browserAction.setIcon({path:b[++f%4]}),setTimeout(function(){k()},500)):c.defaultIcon()};this.running=!0;k()},stop:function(){this.running=!1;this.defaultIcon()},defaultIcon:function(){chrome.browserAction.setIcon({path:"images/sss_19.png"})}}};
d.start();var g=a===cActionMultiPDF?a:cActionSilentAdd,h=-1;a===cActionMultiPDF&&(pluginCommand("startMultiPagePDF"),multiPDFMode=!0);(function(f){return new Promise(function(b){var c=0;chrome.tabs.query({currentWindow:!0},function(k){if(k&&0!==k.length){for(var l=0;l<k.length&&-1===h;++l)k[l].active&&(h=l);var m=0;(new e(function(p){try{chrome.tabs.highlight({windowId:k[m].windowId,tabs:m},function(){checkTabReadyForCapturing(k[m].id,5E3,function(n){n?capturePage(f,cModeEntire,void 0,function(q){q&&
++c;p.next()},k[m++],0):(m++,p.next())})})}catch(n){logError(n.message),b(c)}},function(){return m>=k.length?(b(c),!0):!1})).next()}else b(c)})})})(g).then(function(f){d.stop();a===cActionMultiPDF?(pluginCommand("endMultiPagePDF"),multiPDFMode=void 0):pluginCommand("doGroupAction",{action:a,count:f});0<=h&&chrome.tabs.highlight({tabs:h})})}
function initHandlers(){chrome.tabs.onUpdated.addListener(function(a,e,d){e&&"complete"===e.status&&(/https:\/\/getfireshot(\.com)?\/activate\.php/.test(d.url)||!isCustomBuild()&&!isAPIEnabled()||initAPI("pageLoad"),fInjectGmailScript&&/^https?:\/\/mail.google.com\/mail.*$/.test(d.url)&&(getConsolePtr()("Executing script for: "+d.url),chrome.tabs.executeScript(a,{file:"scripts/3p/inboxsdk.js",runAt:"document_end"},function(){chrome.runtime.lastError&&getConsolePtr()("error:"+chrome.runtime.lastError);
chrome.tabs.executeScript(a,{file:"scripts/fsGmail.js",runAt:"document_end"},function(){chrome.runtime.lastError&&getConsolePtr()("error:"+chrome.runtime.lastError);fInjectGmailScript=!1})})))});chrome.tabs.onActivated.addListener(function(a){(isCustomBuild()||isAPIEnabled())&&initAPI("tabSwitch")});chrome.commands.onCommand.addListener(function(a){getConsolePtr()("Command:",a);"last-used-action"===a&&(fCapturing||shortcutProcessing?fCapturing&&stopCapturing():captureLastUsedMode())})}
function init(){initMessaging();initHandlers();isSafari()&&setOption(cSafariFirstSavePref,"true");document.addEventListener("DOMContentLoaded",function(){restoreBadge();getVersionInfo();updateContextMenu();checkAdvancedUpdates()})}init();
