/*
 FireShot - Webpage Screenshots and Annotations
 Copyright (C) 2007-2021 Evgeny Suslikov (evgeny@suslikov.ru)
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(b,g,h){b instanceof String&&(b=String(b));for(var l=b.length,c=0;c<l;c++){var q=b[c];if(g.call(h,q,c,b))return{i:c,v:q}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,g,h){if(b==Array.prototype||b==Object.prototype)return b;b[g]=h.value;return b};$jscomp.getGlobal=function(b){b=["object"==typeof globalThis&&globalThis,b,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var g=0;g<b.length;++g){var h=b[g];if(h&&h.Math==Math)return h}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(b,g){var h=$jscomp.propertyToPolyfillSymbol[g];if(null==h)return b[g];h=b[h];return void 0!==h?h:b[g]};
$jscomp.polyfill=function(b,g,h,l){g&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(b,g,h,l):$jscomp.polyfillUnisolated(b,g,h,l))};$jscomp.polyfillUnisolated=function(b,g,h,l){h=$jscomp.global;b=b.split(".");for(l=0;l<b.length-1;l++){var c=b[l];if(!(c in h))return;h=h[c]}b=b[b.length-1];l=h[b];g=g(l);g!=l&&null!=g&&$jscomp.defineProperty(h,b,{configurable:!0,writable:!0,value:g})};
$jscomp.polyfillIsolated=function(b,g,h,l){var c=b.split(".");b=1===c.length;l=c[0];l=!b&&l in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var q=0;q<c.length-1;q++){var a=c[q];if(!(a in l))return;l=l[a]}c=c[c.length-1];h=$jscomp.IS_SYMBOL_NATIVE&&"es6"===h?l[c]:null;g=g(h);null!=g&&(b?$jscomp.defineProperty($jscomp.polyfills,c,{configurable:!0,writable:!0,value:g}):g!==h&&($jscomp.propertyToPolyfillSymbol[c]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(c):$jscomp.POLYFILL_PREFIX+c,c=
$jscomp.propertyToPolyfillSymbol[c],$jscomp.defineProperty(l,c,{configurable:!0,writable:!0,value:g})))};$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(g,h){return $jscomp.findInternal(this,g,h).v}},"es6","es3");$jscomp.arrayIteratorImpl=function(b){var g=0;return function(){return g<b.length?{done:!1,value:b[g++]}:{done:!0}}};$jscomp.arrayIterator=function(b){return{next:$jscomp.arrayIteratorImpl(b)}};
$jscomp.makeIterator=function(b){var g="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];return g?g.call(b):$jscomp.arrayIterator(b)};
$jscomp.polyfill("Promise",function(b){function g(){this.batch_=null}function h(a){return a instanceof c?a:new c(function(d,k){d(a)})}if(b&&(!($jscomp.FORCE_POLYFILL_PROMISE||$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION&&"undefined"===typeof $jscomp.global.PromiseRejectionEvent)||!$jscomp.global.Promise||-1===$jscomp.global.Promise.toString().indexOf("[native code]")))return b;g.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var d=this;this.asyncExecuteFunction(function(){d.executeBatch_()})}this.batch_.push(a)};
var l=$jscomp.global.setTimeout;g.prototype.asyncExecuteFunction=function(a){l(a,0)};g.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var d=0;d<a.length;++d){var k=a[d];a[d]=null;try{k()}catch(n){this.asyncThrow_(n)}}}this.batch_=null};g.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var c=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];this.isRejectionHandled_=!1;var d=this.createResolveAndReject_();
try{a(d.resolve,d.reject)}catch(k){d.reject(k)}};c.prototype.createResolveAndReject_=function(){function a(n){return function(r){k||(k=!0,n.call(d,r))}}var d=this,k=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};c.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof c)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var d=null!=a;break a;case "function":d=!0;break a;default:d=!1}d?this.resolveToNonPromiseObj_(a):
this.fulfill_(a)}};c.prototype.resolveToNonPromiseObj_=function(a){var d=void 0;try{d=a.then}catch(k){this.reject_(k);return}"function"==typeof d?this.settleSameAsThenable_(d,a):this.fulfill_(a)};c.prototype.reject_=function(a){this.settle_(2,a)};c.prototype.fulfill_=function(a){this.settle_(1,a)};c.prototype.settle_=function(a,d){if(0!=this.state_)throw Error("Cannot settle("+a+", "+d+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=d;2===this.state_&&this.scheduleUnhandledRejectionCheck_();
this.executeOnSettledCallbacks_()};c.prototype.scheduleUnhandledRejectionCheck_=function(){var a=this;l(function(){if(a.notifyUnhandledRejection_()){var d=$jscomp.global.console;"undefined"!==typeof d&&d.error(a.result_)}},1)};c.prototype.notifyUnhandledRejection_=function(){if(this.isRejectionHandled_)return!1;var a=$jscomp.global.CustomEvent,d=$jscomp.global.Event,k=$jscomp.global.dispatchEvent;if("undefined"===typeof k)return!0;"function"===typeof a?a=new a("unhandledrejection",{cancelable:!0}):
"function"===typeof d?a=new d("unhandledrejection",{cancelable:!0}):(a=$jscomp.global.document.createEvent("CustomEvent"),a.initCustomEvent("unhandledrejection",!1,!0,a));a.promise=this;a.reason=this.result_;return k(a)};c.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=0;a<this.onSettledCallbacks_.length;++a)q.asyncExecute(this.onSettledCallbacks_[a]);this.onSettledCallbacks_=null}};var q=new g;c.prototype.settleSameAsPromise_=function(a){var d=this.createResolveAndReject_();
a.callWhenSettled_(d.resolve,d.reject)};c.prototype.settleSameAsThenable_=function(a,d){var k=this.createResolveAndReject_();try{a.call(d,k.resolve,k.reject)}catch(n){k.reject(n)}};c.prototype.then=function(a,d){function k(u,w){return"function"==typeof u?function(t){try{n(u(t))}catch(z){r(z)}}:w}var n,r,e=new c(function(u,w){n=u;r=w});this.callWhenSettled_(k(a,n),k(d,r));return e};c.prototype.catch=function(a){return this.then(void 0,a)};c.prototype.callWhenSettled_=function(a,d){function k(){switch(n.state_){case 1:a(n.result_);
break;case 2:d(n.result_);break;default:throw Error("Unexpected state: "+n.state_);}}var n=this;null==this.onSettledCallbacks_?q.asyncExecute(k):this.onSettledCallbacks_.push(k);this.isRejectionHandled_=!0};c.resolve=h;c.reject=function(a){return new c(function(d,k){k(a)})};c.race=function(a){return new c(function(d,k){for(var n=$jscomp.makeIterator(a),r=n.next();!r.done;r=n.next())h(r.value).callWhenSettled_(d,k)})};c.all=function(a){var d=$jscomp.makeIterator(a),k=d.next();return k.done?h([]):new c(function(n,
r){function e(t){return function(z){u[t]=z;w--;0==w&&n(u)}}var u=[],w=0;do u.push(void 0),w++,h(k.value).callWhenSettled_(e(u.length-1),r),k=d.next();while(!k.done)})};return c},"es6","es3");
window.addEventListener("load",function(){function b(){e.getAdvancedFeaturesAvailable()||$("#spnAdvancedFeaturesSection").hide();isWindows()&&$("#upgradeLink,#noflashgoadvanced,#noflashgoadvanced2,#noflashgoadvanced3,#divPDFFeatures").removeClass("hiddenInitially");isOpera()?$("#lnkOperaStore").hide():isEdge()?$("#lnkEdgeNew").hide():isSafari()?($("#lnkMSStore").hide(),$("#lnkSafariStore").hide(),$("#pdfCaret").hide()):$("#lnkChromeStore").hide();$("a[href*='APPID']").each(function(){this.href=this.href.replace("APPID",
getBrowserId())});$("#lnkProblem").attr("href","https://getfireshot.com/report-problem.php?u="+btoa(e.tabURL)+"&browser="+getBrowserId()+"&ver="+e.extVersion+"&d="+btoa(JSON.stringify(e.savedCapParamsForDebugging)))}function g(){$("#lnkOptions, #lnkOptions1").click(e.openExtensionPreferences);$("#advancedInstructionsPreDialog").on("hidden.bs.modal",function(){return e.installNative()});$("#lnkInstallAdvancedTop, #lnkUpgradeFromPDF, #lnkInstallAdvanced, #lnkInstallAdvanced1, #lnkInstallAdvancedClipboardDlg").click(function(){$("#advancedInstructionsPreDialog").modal();
return!1});$("#btnCloseAlert1").click(function(){e.setOption("showAlert1",0)});$("#btnSaveImage").click(function(){t.toBlob(function(f){q(f,e.getFilenameLite()+"."+e.getOption(cDefaultImageFormatPref,"png"))},"png"===e.getOption(cDefaultImageFormatPref,"png")?"image/png":"image/jpeg")});$("#btnSaveImagePDF").click(function(f){q((new e.fsPDF(t,z)).toBlob(),e.getFilenameLite()+".pdf")});$("#btnSendEmail").find("li").click(function(){h();var f=$(this).attr("value"),p=f;switch(f){case "png":f=t.toDataURL("image/png");
break;case "jpg":f=t.toDataURL("image/jpeg");break;default:f=(new e.fsPDF(t,z)).toDataURL(),p="pdf"}p=e.getFilenameLite()+"."+p;f={to:"",subject:"Screenshots from FireShot",files:[{inline:"no",name:encodeURIComponent(p),data:f}]};e.openInGmail(JSON.stringify(f))});$("#btnClipboard").click(c);$("#btnPrint").click(function(){l();h()});$("#pdfCaret").click(function(f){f.stopPropagation();$("#ddControl").dropdown("toggle")});$("#menuPDFFeatures").find("li").click(function(f){f.stopPropagation();f=document.getElementById("menuPDFFeatures").getBoundingClientRect();
$("#divUpgradeMsg").css({"min-width":f.width+"px",height:f.height+"px"});$("#divUpgradeMsg").fadeIn(200);return!1});$("#menuPDFFeatures").parent().on("hide.bs.dropdown",function(){return $("#divUpgradeMsg").hide()});$("#btnCloseAdvancedTopMsg").click(function(){e.setOption(cCanBeCapturedBetterNexPref,(new Date).getTime()+864E6);$("#divCanBeBetterPromo").fadeOut(300)});$("#btnCloseAdvertising").click(function(){$("#divAdvertising").hide()});$("#lnkAdPromo").click(function(){return openURL("#")});$("#lnkTest1").click(function(){return a()});
$("#lnkTest2").click(function(){return k()});$("#lnkTest3").click(function(){return d()})}function h(){"true"===e.getOption(cCloseTabAfterSaving)&&chrome.tabs.getCurrent(function(f){return chrome.tabs.remove(f.id)})}function l(){var f=document.createElement("img");f.id="imgForPrinting";f.src=document.getElementById("imgResult").src;f.onload=function(){$("div.container").addClass("noPrint");print();$("div.container").removeClass("noPrint");document.body.removeChild(f)};document.body.appendChild(f)}
function c(){B.then(function(f){try{var p=new ClipboardItem(Object.defineProperty({},f.type,{value:f,enumerable:!0}));return navigator.clipboard.write([p])}catch(m){throw m;}}).then(function(){$("#divClipboardMessage").slideDown(200);setTimeout(function(){return $("#divClipboardMessage").slideUp(100)},2E3);"true"===e.getOption(cCloseTabAfterSaving)&&setTimeout(h,500)}).catch(function(f){getConsolePtr()(f);$("#modalCopyToClipboard").modal()})}function q(f,p,m){if(isSafari()){var y=new FileReader;y.onloadend=
function(){var v=document.createElementNS("http://www.w3.org/1999/xhtml","iframe");v.style.cssText="position:absolute; left: -10000px; visibility:hidden";document.body.appendChild(v);var x=v.contentDocument.createElement("a");v.contentDocument.body.appendChild(x);var E=y.result.replace(/^data:[^;]*;/,"data:attachment/file;");x.download=p;x.href=E;if("true"!==e.getOption(cSafariFirstSavePref)){var C;getConsolePtr()("Trying to prevent auto-close event.");var D=function(){getConsolePtr()("Cancelling window auto-close.");
window.removeEventListener("blur",D,!1);clearTimeout(C)};window.addEventListener("blur",D,!1);x.addEventListener("click",function(){C=setTimeout(h,1500)})}else e.setOption(cSafariFirstSavePref,"false");x.click();setTimeout(function(){document.body.removeChild(v)},2E3)};y.readAsDataURL(f)}else addDownloadsPermission(function(){w||(w=!0,chrome.downloads.onChanged.addListener(function(x){x.state&&"complete"==x.state.current&&("true"===e.getOption(cOpenFolderAterSavingPref)&&chrome.downloads.show(u),
h())}));var v=/^\/*(.*?)\/*$/g.exec(e.getOption(cDefaultFolderPref,cDefaultFolderValue))[1];""!==v&&(v+="/");chrome.downloads.download({url:URL.createObjectURL(f),saveAs:"true"!==e.getOption(cNoFilenamePromptPref),filename:m?p:v+p,conflictAction:"overwrite"},function(x){chrome.runtime.lastError?m||q(f,p,!0):u=x})})}function a(){$("#btnLike #btnDislike").unbind();$("#btnLike").click(function(){e.setOption(cLikedPref,"true");$("#divLikeMessage").hide();k()});$("#btnDislike").click(function(){e.setOption(cLikedPref,
"false");$("#divLikeMessage").slideUp(100)});setTimeout(function(){$("#divLikeMessage").slideDown(300)},2E3)}function d(){return parseInt(e.getOption(cCanBeCapturedBetterNexPref,"0"))<=(new Date).getTime()?(setTimeout(function(){return $("#divCanBeBetterPromo").slideDown(300)},isDebug?0:2E3),!0):!1}function k(){$("#btnRate #btnRateLater").unbind();$("#btnRate").click(function(){e.setOption(cRatedPref,"true");$("#divSendReview").slideUp(100);openURL("https://getfireshot.com/like.php?browser="+getBrowserId()+
"&ver="+e.extVersion)});$("#btnRateLater").click(function(){$("#divSendReview").slideUp(100)});setTimeout(function(){$("#divSendReview").slideDown(300)},200)}function n(){if(isWindows()&&""!==e.getOption(cPluginProModePref,"")&&""===e.getOption("showAlert1",""))setTimeout(function(){$("#divAlert1").fadeIn(700)},1E3);else{var f="true"===e.getOption(cLikedPref,""),p=""!==e.getOption(cLikedPref,""),m="true"===e.getOption(cRatedPref,"false"),y=parseInt(e.getOption(cResultPageShownCntrPref,0));!p&&10<
y?a():f&&!m&&0===y%50&&k()}}function r(){function f(){var m=document.getElementById("divImgResult"),y=m.getClientRects()[0],v=document.getElementById("divPanel").getClientRects()[0];y.y+y.height<v.y?($("#divImgResult").height($("#divPanel").height()),$("#divImgResult").css("overflow-y",m.clientHeight<m.scrollHeight?"scroll":"hidden"),$("#divPanel").width($("#divImgResult").width())):($("#divImgResult").height("auto"),$("#divPanel").width($("#divContainer").width()-$("#divImgResult").width()-40));
t.width<$(m).width()-20?($("#imgResult").css("width","auto"),$("#divImgResult").css("overflow-y",m.clientHeight<m.scrollHeight?"scroll":"hidden"),m.style.zoom=1.0000001,setTimeout(function(){m.style.zoom=1},50)):m.clientHeight>=m.scrollHeight&&($(m).css("overflow-y","hidden"),m.style.zoom=1.0000001,setTimeout(function(){m.style.zoom=1},50))}$(window).resize(f);$(window).scroll(function(){$("#divLeftCol").offset().top-15<window.scrollY&&$("#divImgResult").height()>$("#divPanel").height()&&$("#divPanel").height()<
window.innerHeight?($("#divPanel").addClass("fixed"),$("#divPanel").css({top:"15px"})):$("#divPanel").removeClass("fixed")});var p=0===e.getOption(cTemplateNumberPref,1)%5;setTimeout(function(){$("#lnkSiteIndex").addClass("splashIn")},p?1800:1E3);isWindows()&&(!A||A&&!d())&&(p?setTimeout(function(){return $("#divPromo").slideDown(300)},1E3):$("#divPromo").show());document.title=e.getFilenameLite();p=document.getElementById("imgResult");p.onload=function(){setTimeout(f,10);$("#divPreload").hide();
$("#divContainer").show()};p.src=t.toDataURL("image/jpeg")}var e=null,u,w=!1,t,z,B,A;(function(){try{i18nPrepare()}catch(f){logError(f.message)}chrome.runtime.getBackgroundPage(function(f){f&&(e=f,e.setOption(cResultPageShownCntrPref,parseInt(e.getOption(cResultPageShownCntrPref,0))+1),t=e.capResult,z=e.capLinks||[],A=e.canBeBetter,B=new Promise(function(p){t.toBlob(function(m){return p(m)},"image/png")}),b(),g(),r(),n())})})()});
