/*
 FireShot - Webpage Screenshots and Annotations
 Copyright (C) 2007-2021 Evgeny Suslikov (evgeny@suslikov.ru)
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};
$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};$jscomp.polyfillUnisolated=function(a,b,c,d){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var h=a[d];if(!(h in c))return;c=c[h]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,d){var h=a.split(".");a=1===h.length;d=h[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var k=0;k<h.length-1;k++){var g=h[k];if(!(g in d))return;d=d[g]}h=h[h.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?d[h]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,h,{configurable:!0,writable:!0,value:b}):b!==c&&($jscomp.propertyToPolyfillSymbol[h]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(h):$jscomp.POLYFILL_PREFIX+h,h=
$jscomp.propertyToPolyfillSymbol[h],$jscomp.defineProperty(d,h,{configurable:!0,writable:!0,value:b})))};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(h,k){this.$jscomp$symbol$id_=h;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:k})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var c=0,d=function(h){if(this instanceof d)throw new TypeError("Symbol is not a constructor");return new b("jscomp_symbol_"+(h||"")+"_"+c++,h)};return d},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=$jscomp.global[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&$jscomp.defineProperty(d.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,h={next:function(){if(!d&&c<a.length){var k=c++;return{value:b(k,a[k]),done:!1}}d=!0;return{done:!0,value:void 0}}};h[Symbol.iterator]=function(){return h};return h};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(b){return b})}},"es6","es3");
var scriptLoaded=!0,stubbornNodes=[],changedNodes=[],stickyNodes=[],floatingElements=[],commPortName,options,sbStyle,lockedScrollEvent,ignoredAttributeFlagName="__fireshotIgnoredElement",prevPosXFlagName="__fireshotPosX",prevPosYFlagName="__fireshotPosY",analysisCountName="__fireshotCheckedCntr",canBeBetter,fsSelectionHint,fNative;chrome.runtime.sendMessage&&chrome.runtime.sendMessage({message:"getPortName"},function(a){commPortName=a.portName;getConsolePtr()("Obtained port name: "+commPortName)});
function getOptionFromScript(a,b){return options[a]||b}var addRule=function(a){var b=document.head.appendChild(a).sheet;return function(c,d){var h="string"===typeof d?d:Object.keys(d).map(function(g){return g+":"+("content"===g?"'"+d[g]+"'":d[g])}).join(";"),k=b.insertRule(c+"{"+h+"}",b.cssRules.length);return{cancel:function(){b.removeRule(k)}}}}(document.createElement("style"));
function enableSomeElements(a){"undefined"===typeof a&&(a=!0);var b;if(window.location.href.match(/https?:\/\/mail\.google\.com/i)){for(var c=document.createNodeIterator(document.body,NodeFilter.SHOW_ELEMENT,null,!1),d;d=c.nextNode();)"TD"==d.nodeName&&d.getAttribute("class")&&d.getAttribute("class").match(/Bu y3/i)&&d.style.setProperty("display",a?"":"none","important");(b=document.getElementById(":ro"))&&b.style.setProperty("display",a?"":"none","important");(b=document.getElementById(":5"))&&b.style.setProperty("display",
a?"":"none","important")}}function safeChangeElementStyleProperty(a,b,c,d){a.unshift({object:b,property:c,value:b.style.getPropertyValue(c),priority:b.style.getPropertyPriority(c)});b.style.setProperty(c,d,"important");getConsolePtr()("Changing: ");getConsolePtr()(b);getConsolePtr()("Setting element.style['"+c+"'] = '"+d+"'")}
function restoreChangedStyles(a){a.forEach(function(b){b.value?b.object.style.setProperty(b.property,b.value,b.priority):b.object.style[b.property]=null;getConsolePtr()("Restoring: ");getConsolePtr()(b.object);getConsolePtr()("Setting element.style['"+b.property+"'] = '"+b.value+"'")});a.length=0}
function hideObtrusiveElements(a,b){for(var c=a.getBoundingClientRect(),d=window.innerWidth*window.innerHeight+1,h=c.width*c.height+1,k=document.createNodeIterator(document.body,NodeFilter.SHOW_ELEMENT,null,!1),g=a!==getScrollingElement(),q=.9*window.innerWidth,m=.9*window.innerHeight,u=.33*c.width,r=.33*c.height;null!==(c=k.nextNode());)if("1"!==c.getAttribute(ignoredAttributeFlagName)){var l="undefined"!==typeof c[analysisCountName]?c[analysisCountName]:0;if(!(2<l))if(c[analysisCountName]=++l,l=
c.getBoundingClientRect(),c.scrollWidth>q&&c.scrollHeight>m&&c.clientWidth>u&&c.clientHeight>r)c.setAttribute(ignoredAttributeFlagName,"1");else{var w=l.width*l.height;if(0===w||.35<w/d)c.setAttribute(ignoredAttributeFlagName,"1");else{w=c.getAttribute(prevPosXFlagName);var G=c.getAttribute(prevPosYFlagName);if(void 0===w)c.setAttribute(prevPosXFlagName,l.left),c.getAttribute(prevPosYFlagName,l.top);else if(!(!(!b&&G==l.top||b&&w==l.left)||elementInHiddenList(c)||c===a||g&&isChildOf(c,a)||g&&isChildOf(a,
c)&&.35<l.width*l.height/h)){a:{for(l=c;l&&l!=document;){w=document.defaultView.getComputedStyle(l,"");if("hidden"===w.visibility||"none"===w.display||"0"===w.opacity){l=!0;break a}l=l.parentNode}l=!1}l?c.setAttribute(ignoredAttributeFlagName,"1"):hideElement(c)}}}}}function elementInHiddenList(a){for(var b=0;b<stubbornNodes.length;++b)if(stubbornNodes[b].elem===a)return!0;return!1}
function hideElement(a){getConsolePtr()("Hiding:");getConsolePtr()(a);stubbornNodes.push({elem:a,opacity:a.style.getPropertyValue("opacity"),animation:a.style.getPropertyValue("animation"),transitionDuration:a.style.getPropertyValue("transition-duration")});a.style.setProperty("opacity","0");a.style.setProperty("animation","unset");a.style.setProperty("transition-duration","0s");a.setAttribute(ignoredAttributeFlagName,"1")}
function hideStubbornElements(a,b){var c=a?a.getBoundingClientRect():void 0,d=c?c.width:window.innerWidth;c=c?c.height:window.innerHeight;b=b||!1;for(var h=document.createNodeIterator(document.body,NodeFilter.SHOW_ELEMENT,null,!1),k;k=h.nextNode();)if(!fsSelectionHint||k!=fsSelectionHint.holder){var g=document.defaultView.getComputedStyle(k,""),q=g&&g.getPropertyValue("position");if(!("fixed"!=q&&"sticky"!=q||elementInHiddenList(k)||"none"==g.getPropertyValue("display")||a&&isChildOf(k,a)||"sticky"!=
q&&b&&k.scrollWidth>window.innerWidth||k.scrollWidth>.9*window.innerWidth&&k.scrollHeight>.9*window.innerHeight&&k.clientWidth>.33*d&&k.clientHeight>.33*c)){var m=!1;if("sticky"===q){var u=g.getPropertyValue("top"),r=g.getPropertyValue("bottom"),l=g.getPropertyValue("left");g=g.getPropertyValue("right");u&&"-3e+07px"!==u&&(fNative?safeChangeElementStyleProperty(stickyNodes,k,"top","-3e+07px"):m=!0);r&&"-3e+07px"!==r&&(fNative?safeChangeElementStyleProperty(stickyNodes,k,"bottom","-3e+07px"):m=!0);
l&&"-3e+07px"!==l&&(fNative?safeChangeElementStyleProperty(stickyNodes,k,"left","-3e+07px"):m=!0);g&&"-3e+07px"!==g&&(fNative?safeChangeElementStyleProperty(stickyNodes,k,"right","-3e+07px"):m=!0)}canBeBetter|=m;if(m||"sticky"!==q)getConsolePtr()("Found stubborn element "+k.id),hideElement(k)}}for(a=0;a<stubbornNodes.length;++a)stubbornNodes[a].elem.style.setProperty("opacity","0")}
function showHiddenElements(){for(var a=0;a<stubbornNodes.length;++a)stubbornNodes[a].elem.style.setProperty("opacity",stubbornNodes[a].opacity),stubbornNodes[a].elem.style.setProperty("animation",stubbornNodes[a].animation),stubbornNodes[a].elem.style.setProperty("transition-duration",stubbornNodes[a].transitionDuration)}
function removeCustomAttributes(){for(var a=document.createNodeIterator(document.body,NodeFilter.SHOW_ELEMENT,null,!1),b;b=a.nextNode();)b.removeAttribute(ignoredAttributeFlagName),b.removeAttribute(prevPosXFlagName),b.removeAttribute(prevPosYFlagName),"undefined"!==typeof b[analysisCountName]&&delete b[analysisCountName]}
function disableFixedBackgrounds(){for(var a=document.createNodeIterator(document.body,NodeFilter.SHOW_ELEMENT,null,!1),b;null!==(b=a.nextNode());)"fixed"==document.defaultView.getComputedStyle(b,"").backgroundAttachment&&safeChangeElementStyleProperty(changedNodes,b,"background-attachment","scroll")}
function FBAdapter(){var a=[];(function(){a=Array.prototype.slice.call(document.querySelectorAll("DIV")).map(function(b){return{element:b,top:b.style.top}}).filter(function(b){return"absolute"==b.element.style.position})})();return{undoSwitchingToFixedPositions:function(){a.forEach(function(b){"fixed"==b.element.style.position&&(b.element.style.position="absolute",b.element.style.top=b.top)})}}}
function getAltExtents(){var a=window.document,b=a.documentElement;b=b.clientWidth?b.clientWidth:window.innerWidth;var c=-1;0>c&&(c=window.innerHeight-getSBHeight(window));if(a.body){var d="CSS1Compat"==a.compatMode?a.documentElement.scrollWidth:a.body.scrollWidth,h=a.documentElement.scrollHeight,k="CSS1Compat"==a.compatMode?a.documentElement.clientWidth:a.body.clientWidth;a="CSS1Compat"==a.compatMode?a.documentElement.clientHeight:a.body.clientHeight;d<k&&(d=k);h<a&&(h=a);b<d&&(b=d);c<h&&(c=h)}return{Width:b,
Height:c}}
function findScrolledElement(a,b){for(var c=document,d,h=location.href,k=document.createNodeIterator(document.body,NodeFilter.SHOW_ELEMENT,null,!1),g;null!==(g=k.nextNode());)if(0<g.scrollWidth&&0<g.scrollHeight&&(g.scrollWidth>g.clientWidth||g.scrollHeight>g.clientHeight)&&(h.match(/https?:\/\/www\.(facebook|fb)\.com/i)&&g.scrollHeight>.5*b||g.scrollWidth>a&&g.scrollHeight>.5*b||g.scrollHeight>b&&g.scrollWidth>.3*a||g.clientWidth>.7*a&&g.clientHeight>.7*b)){var q=c.defaultView.getComputedStyle(g,"");
isScrollableStyle(q)&&(!d||d.scrollWidth*d.scrollHeight<g.scrollWidth*g.scrollHeight)&&(q=getElementExtents(g),q.absoluteX+q.w<=window.innerWidth+2&&(q.absoluteY+q.h<=window.innerHeight+2||1.5*window.innerHeight<g.scrollHeight&&g.clientHeight<=window.innerHeight+50)&&(!d||d.scrollWidth*d.scrollHeight<g.scrollWidth*g.scrollHeight)&&(d=g))}d&&(getConsolePtr()("Found scrolled element:"),getConsolePtr()(d));return d}
function getElementExtents(a){var b=a.getClientRects(),c={absoluteX:0,absoluteY:0,x:0,y:0,w:0,h:0};0<b.length&&(c.absoluteX=a.clientLeft+b[0].left,c.absoluteY=a.clientTop+b[0].top,c.w=b[0].width,c.h=b[0].height);return c}
function disableFloatingInView(a){floatingElements=[];for(var b=document,c=getElementExtents(a),d=window.innerWidth*window.innerHeight+1,h=b.createNodeIterator(b.body,NodeFilter.SHOW_ELEMENT,null,!1),k;null!==(k=h.nextNode());){var g=b.defaultView.getComputedStyle(k,"");!g||"0"===g.getPropertyValue("opacity")||"absolute"!=g.getPropertyValue("position")&&"relative"!=g.getPropertyValue("position")||(g=getElementExtents(k),0===g.w*g.h||.35<g.w*g.h/d||k==a||!getIntersection(c.absoluteX,c.absoluteY,c.w,
c.h,g.absoluteX,g.absoluteY,g.w,g.h)||isChildOf(a,k)||isChildOf(k,a)||(getConsolePtr()("Hiding:"),getConsolePtr()(k),safeChangeElementStyleProperty(floatingElements,k,"opacity","0")))}}function disableScrollEvent(){}function enableScrollEvent(){window.removeEventListener("scroll",lockedScrollEvent,!0)}
function getOffsets(a,b,c){var d={x:0,y:0};b===cModeVisible?(d.x=getScrollingElement().scrollLeft,d.y=getScrollingElement().scrollTop):b===cModeSelected?(d.x=c.left,d.y=c.top):a.div&&(d.x=a.left,d.y=a.top);return d}function getScrollingElement(){return document.scrollingElement||document.body}
chrome.runtime.onConnect.addListener(function(a){function b(f,E){options[f]=E;a.postMessage({topic:"setOption",optionName:f,optionValue:E})}function c(f,E){n=E;m=f;e=getScrollingElement();m!=cModeEntire||n||h||(n=findScrolledElement(e.scrollWidth,e.scrollHeight));D=n||J.body;n&&(e=n,n.scrollIntoView(),disableFloatingInView(n),T=n.style.zIndex,n.style.zIndex=2147483647);U=e.scrollTop;V=e.scrollLeft;y=e.scrollWidth;v=e.scrollHeight;K=H=L=M=void 0;if(!n){"hidden"===document.defaultView.getComputedStyle(document.body,
"").overflowX&&(H=D.style.overflowX,f=e.scrollHeight,D.style.overflowX="visible",f>=e.scrollHeight&&(D.style.overflowX=H,H=void 0));y=Math.max(J.documentElement.scrollWidth,D.scrollWidth,document.documentElement.clientWidth,D.offsetWidth,document.documentElement.offsetWidth);v=Math.max(J.documentElement.scrollHeight,D.scrollHeight,document.documentElement.clientHeight,D.offsetHeight,document.documentElement.offsetHeight);if(0>=y||0>=v)f=getAltExtents(),y=f.Width,v=f.Height;0>=y&&(y=1024);0>=v&&(v=
768)}m===cModeEntire&&(k?(e.scrollTop=1,e.scrollLeft=1,setTimeout(function(){e.scrollTop=0;e.scrollLeft=0},10)):(e.scrollTop=0,e.scrollLeft=0));N&&(W=FBAdapter());m!==cModeVisible&&m!==cModeBrowser&&enableSomeElements(!1);n?(F=n.clientWidth,C=n.clientHeight):(F=window.innerWidth,C=window.innerHeight,y<window.innerWidth&&(y=window.innerWidth))}if(chrome.runtime.sendMessage&&a.name!=commPortName)getConsolePtr()("Comm port name is wrong: "+a.name+" <> "+commPortName);else{var d=!0,h=!1,k=0===window.navigator.plugins.length&&
isConsoleOpened(),g=1,q=1,m=0,u=0,r=1,l=1,w=!0,G=!0,F=0,C=0,O=0,P=0,X=0,Y=0,p={left:0,top:0,right:0,bottom:0},n,J,D,e,U,V,H,M,L,Q,y,v,T,Z,z,N=window.location.href.match(/https?:\/\/www\.(facebook|fb)\.com/i),W,K,R,S,I;a.onMessage.addListener(function(f){switch(f.topic){case "init":Z=f.p;fNative=f.native;window.isDebug|=f.debug;u=Z?150:200;J=window.document;options=JSON.parse(f.options);h=f.frameMode;stubbornNodes=[];changedNodes=[];stickyNodes=[];R=u/((parseInt(getOptionFromScript(cPageScrollingSpeedPref,
100))||100)/100);S=fNative&&"true"===getOptionFromScript(cAllowInfiniteScrolling,"true");canBeBetter=!1;try{c(f.mode)}catch(t){getConsolePtr()(t.stack);a.postMessage({topic:"initAborted"});return}disableFixedBackgrounds();Q=document.defaultView.getComputedStyle(document.documentElement,"").scrollBehavior;""!=Q&&(document.documentElement.style.scrollBehavior="initial");N||disableScrollEvent();if(m!==cModeSelected&&!n||k)K=addRule("body::-webkit-scrollbar",{display:"none"}),safeChangeElementStyleProperty(changedNodes,
window.document.documentElement,"scrollbar-width","none"),document.scrollingElement?v=Math.max(v,document.scrollingElement.scrollHeight):(L=document.defaultView.getComputedStyle(document.documentElement,"").overflowY,document.documentElement.style.overflowY="initial",M=document.defaultView.getComputedStyle(document.documentElement,"").overflowX,document.documentElement.style.overflowX="initial");var E={topic:"initDone",url:document.location.toString(),title:document.title,cw:h&&frameElement?frames.parent.innerWidth:
window.innerWidth,ch:h&&frameElement?frames.parent.innerHeight:window.innerHeight,emulation:k};N&&m===cModeEntire?setTimeout(function(){e.scrollTop=v;setTimeout(function(){e.scrollTop=0;setTimeout(function(){a.postMessage(E)},u)},u)},u):setTimeout(function(){a.postMessage(E)},u);break;case "setRatio":r=f.ratioW;l=f.ratioH;getConsolePtr()("Ratios: "+r+", "+l);break;case "cancelSelection":I&&I.cancel();break;case "selectArea":if(!document.body){alert("Apologies, this page does not support capturing selections.");
a.postMessage({topic:"areaSelectionCanceled"});enableScrollEvent();break}fNative||hideStubbornElements();if(0!==e.scrollTop){var A=e.scrollTop;e.scrollTop=0;hideObtrusiveElements(e,!1);e.scrollTop=A}else hideObtrusiveElements(e,!1);fsSelectionHint=FireShotAddon.FSSelectionHint(document);fNative&&"false"!==getOptionFromScript(cShowSelectionHintPref,"true")&&fsSelectionHint.show();I=FireShotAddon.FSSelector({browser:"chrome",extendedMode:fNative,doc:document,ignoredAttributeFlagName:ignoredAttributeFlagName,
onScroll:function(){fNative&&(0===e.scrollTop?showHiddenElements():(hideStubbornElements(),hideObtrusiveElements(e,!1)))}});I.makeSelection(function(t){fNative&&(fsSelectionHint.isShown()?fsSelectionHint.hide():b(cShowSelectionHintPref,"false"));t.left==t.right||t.top==t.bottom?(a.postMessage({topic:"areaSelectionCanceled"}),showHiddenElements(),fNative&&restoreChangedStyles(stickyNodes),removeCustomAttributes(),enableScrollEvent()):(canBeBetter|=200<e.scrollHeight-e.scrollHeight,fNative&&(v=Math.max(v,
e.scrollHeight),showHiddenElements(),restoreChangedStyles(stickyNodes)),t.isScrollable?(getConsolePtr()("Capturing element:"),getConsolePtr()(t.selectedElement),c(cModeEntire,t.selectedElement)):(e.scrollLeft=t.left,e.scrollTop=Math.max(0,t.top-150),O=e.scrollLeft,P=e.scrollTop,p.left=t.left,p.top=t.top,p.right=t.right,p.bottom=t.bottom),setTimeout(function(){if(!fNative)hideStubbornElements();else if(0!==e.scrollTop){var aa=e.scrollTop;e.scrollTop=0;hideObtrusiveElements(e,!1);e.scrollTop=aa;hideStubbornElements()}a.postMessage({topic:"areaSelected"})},
u));I=void 0});break;case "scrollNext":if(d){z=new LinksGrabber(n||document);z.clearAttributes();z.markHiddenLinks();z.createLinksSnapshot();hideObtrusiveElements(e,!1);0===e.scrollLeft&&0===e.scrollTop&&z.checkClickableLinks();d=!1;setTimeout(function(){try{a.postMessage({topic:"scrollDone",x:e.scrollLeft*r,y:e.scrollTop*l})}catch(t){console.log(t)}},u);return}if(!f.cancel&&w&&m!=cModeVisible&&m!=cModeBrowser){var ba=m==cModeSelected?p.right:y;var B=Math.max(F-30,0);var x=e.scrollLeft;e.scrollLeft+=
Math.max(0,Math.min(B,ba-(e.scrollLeft+B)+20));if(w=e.scrollLeft!=x&&e.scrollLeft<y){1==g&&q++;getConsolePtr()("scrollLeft:"+e.scrollLeft);setTimeout(function(){hideStubbornElements(n,!0);hideObtrusiveElements(e,!0);z.createLinksSnapshot();setTimeout(function(){a.postMessage({topic:"scrollDone",x:e.scrollLeft*r,y:e.scrollTop*l})},u+R)},0);return}m==cModeSelected&&(X=e.scrollLeft)}if(!f.cancel&&G&&m!=cModeVisible&&m!=cModeBrowser&&(B=C-(0===e.scrollTop?150:40),0>=B&&(B=C),0<B-150&&(B-=150),x=e.scrollTop,
e.scrollTop+=B,G=x!=e.scrollTop&&(S||e.scrollTop<v),m==cModeSelected&&((G&=e.scrollTop<p.bottom)||(Y=x)),G)){g++;e.scrollLeft=m==cModeEntire?0:O;getConsolePtr()("scrollTop:"+e.scrollTop);w=!0;setTimeout(function(){N&&W.undoSwitchingToFixedPositions();hideStubbornElements(n);hideObtrusiveElements(e,!1);z.createLinksSnapshot();setTimeout(function(){a.postMessage({topic:"scrollDone",x:e.scrollLeft*r,y:e.scrollTop*l})},u+R)},10);return}f.cancel&&getConsolePtr()("Capturing canceled");if(f.cancel||S)v=
Math.max(e.scrollTop+C,v);f={topic:"scrollFinished",div:0,left:0,top:0,width:m==cModeEntire?y:F,height:m==cModeEntire?v:C,ratioW:r,ratioH:l,rows:g,cols:q,cw:F,ch:C,hScrollbar:window.innerHeight>C,vScrollBar:window.innerWidth>F,cropLeft:0,cropRight:0,cropTop:0,cropBottom:0,canBeBetter:canBeBetter&&m!==cModeVisible};h&&frameElement?(f.div=1,f.left=frameElement.clientLeft+frameElement.offsetLeft,f.top=frameElement.clientTop+frameElement.offsetTop):n&&(x=n.getClientRects(),f.div=1,0<x.length&&(f.left=
n.clientLeft+x[0].left,f.top=n.clientTop+x[0].top),n.style.zIndex=T);restoreChangedStyles(floatingElements);m===cModeSelected&&(f.width=X-O+F,f.height=Y-P+C,f.crop=!0,f.cropLeft=p.left-O,f.cropTop=p.top-P,f.cropRight=f.cropLeft+(p.right-p.left),f.cropBottom=f.cropTop+(p.bottom-p.top));getConsolePtr()(JSON.stringify(f));x=getOffsets(f,m,p);z.getLinks(f,x);z.clearAttributes();z=void 0;e.scrollLeft=0;e.scrollTop=0;m===cModeSelected?A=new fsRect(p.left,p.top,p.right-p.left,p.bottom-p.top):m===cModeVisible&&
(A=new fsRect(x.x,x.y,f.width,f.height));B=new TextGrabber(e);f.words=B.getElements(x,r,l,A);f.left*=r;f.top*=l;f.width*=r;f.height*=l;f.cw*=r;f.ch*=l;f.cropLeft*=r;f.cropTop*=l;f.cropRight*=r;f.cropBottom*=l;e.scrollLeft=V;e.scrollTop=U;restoreChangedStyles(changedNodes);restoreChangedStyles(stickyNodes);document.documentElement.style.scrollBehavior=Q;void 0!==H&&(document.body.style.overflowX=H);void 0!==L&&(document.documentElement.style.overflowY=L);void 0!==M&&(document.documentElement.style.overflowX=
M);enableScrollEvent();m!=cModeVisible&&m!=cModeBrowser&&enableSomeElements(!0);showHiddenElements();removeCustomAttributes();K&&K.cancel();setTimeout(function(){a.postMessage(f)},u);break;case "sendFireShotCaptureCompleteEvent":window.fsPendingCB&&(A={cbId:window.fsPendingCB,data:f.data},"undefined"!==typeof cloneInto&&(A=cloneInto(A,document.defaultView)),A=new document.defaultView.CustomEvent("FireShotCaptureCompleteEvent",{detail:A}),document.dispatchEvent(A))}getConsolePtr()("CS:"+f.topic)})}});
