/*
 FireShot - Webpage Screenshots and Annotations
 Copyright (C) 2007-2021 Evgeny Suslikov (evgeny@suslikov.ru)
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(d,k,l){if(d==Array.prototype||d==Object.prototype)return d;d[k]=l.value;return d};
$jscomp.getGlobal=function(d){d=["object"==typeof globalThis&&globalThis,d,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var k=0;k<d.length;++k){var l=d[k];if(l&&l.Math==Math)return l}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(d,k){var l=$jscomp.propertyToPolyfillSymbol[k];if(null==l)return d[k];l=d[l];return void 0!==l?l:d[k]};$jscomp.polyfill=function(d,k,l,r){k&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(d,k,l,r):$jscomp.polyfillUnisolated(d,k,l,r))};
$jscomp.polyfillUnisolated=function(d,k,l,r){l=$jscomp.global;d=d.split(".");for(r=0;r<d.length-1;r++){var m=d[r];if(!(m in l))return;l=l[m]}d=d[d.length-1];r=l[d];k=k(r);k!=r&&null!=k&&$jscomp.defineProperty(l,d,{configurable:!0,writable:!0,value:k})};
$jscomp.polyfillIsolated=function(d,k,l,r){var m=d.split(".");d=1===m.length;r=m[0];r=!d&&r in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var b=0;b<m.length-1;b++){var n=m[b];if(!(n in r))return;r=r[n]}m=m[m.length-1];l=$jscomp.IS_SYMBOL_NATIVE&&"es6"===l?r[m]:null;k=k(l);null!=k&&(d?$jscomp.defineProperty($jscomp.polyfills,m,{configurable:!0,writable:!0,value:k}):k!==l&&($jscomp.propertyToPolyfillSymbol[m]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(m):$jscomp.POLYFILL_PREFIX+m,m=
$jscomp.propertyToPolyfillSymbol[m],$jscomp.defineProperty(r,m,{configurable:!0,writable:!0,value:k})))};$jscomp.polyfill("Array.from",function(d){return d?d:function(k,l,r){l=null!=l?l:function(a){return a};var m=[],b="undefined"!=typeof Symbol&&Symbol.iterator&&k[Symbol.iterator];if("function"==typeof b){k=b.call(k);for(var n=0;!(b=k.next()).done;)m.push(l.call(r,b.value,n++))}else for(b=k.length,n=0;n<b;n++)m.push(l.call(r,k[n],n));return m}},"es6","es3");
function fsRect(d,k,l,r){return{left:d,top:k,width:l,height:r,fromCSSClip:function(m){m=m.match(/\d+/g);4===m.length&&(this.left=m[3],this.top=m[0],this.width=m[1]-m[3],this.height=m[2]-m[0]);return this}}}
function LinksGrabber(d){var k=document,l=d==document?getScrollingElement():d,r=function(b){var n=k.defaultView.getComputedStyle(b,"");if(!n||"hidden"!==n.getPropertyValue("overflow")&&"hidden"!==n.getPropertyValue("overflow-y")&&"auto"!==n.getPropertyValue("overflow-y")&&"scroll"!=n.getPropertyValue("overflow-y")&&"hidden"!==n.getPropertyValue("overflow-x")&&"auto"!==n.getPropertyValue("overflow-x")&&"scroll"!=n.getPropertyValue("overflow-x"))return m(b.children[0],d)},m=function(b,n){b=b.getBoundingClientRect();
return{top:Math.round(b.top+(window.pageYOffset||l.scrollTop)),left:Math.round(b.left+(window.pageXOffset||l.scrollLeft)),width:b.width,height:b.height}};return{collectedLinks:[],markHiddenLinks:function(){for(var b=[],n=k.createNodeIterator(d==document?d.body:d,NodeFilter.SHOW_ELEMENT,null,!1),a;a=n.nextNode();)if(a.childElementCount&&"HTML"!==a.tagName&&"BODY"!==a.tagName&&a!==d&&(a.offsetHeight<a.scrollHeight||a.offsetWidth<a.scrollWidth)){var e=k.defaultView.getComputedStyle(a,"");!e||"none"===
e.getPropertyValue("display")||"hidden"!==e.getPropertyValue("overflow")&&"hidden"!==e.getPropertyValue("overflow-y")&&"auto"!==e.getPropertyValue("overflow-y")&&"scroll"!=e.getPropertyValue("overflow-y")&&"hidden"!==e.getPropertyValue("overflow-x")&&"auto"!==e.getPropertyValue("overflow-x")&&"scroll"!=e.getPropertyValue("overflow-x")||b.push(a)}b.forEach(function(h){var f=m(h,d);h=h.getElementsByTagName("a");for(var q=0,t=0;t<h.length;++t){var c=h[t],p=m(c,d);rectsIntersected(f,p)||(c.setAttribute("__fireshotHiddenLink",
1),++q)}})},createLinksSnapshot:function(){function b(c){if(c.getAttribute("__fireshotHiddenLink"))return!1;var p;if(p=c.href&&""!==c.href&&!/javascript:.*/.test(c.href)&&c.href.slice&&"#"!==c.href.slice(-1)){a:{for(;c&&c!=k;){p=k.defaultView.getComputedStyle(c,"");if("hidden"===p.visibility||"none"===p.display||"0"===p.opacity){c=!0;break a}c=c.parentNode}c=!1}p=!c}return p}function n(c,p){var v=m(c,d),g=Array.from(c.getClientRects());if(1===g.length){var u;c.children&&0<c.children.length&&"IMG"===
c.children[0].tagName&&(u=r(c))&&0<u.width&&0<u.height?p.push(u):p.push(v)}else if(c.children&&0<c.children.length)for(g=[],g=0;g<c.children.length;g++)v=m(c.children[g]),0<v.width&&0<v.height&&p.push(v);else{g=g.filter(function(w){return 0<w.width&&0<w.height});for(c=0;c<g.length;++c)if(0===c)var x={left:g[c].left,top:g[c].top};else g[c].left<x.left&&(x.left=g[c].left),g[c].top<x.top&&(x.top=g[c].top);if(x)for(u=v.left-x.left,v=v.top-x.top,c=0;c<g.length;++c)p.push({left:g[c].left+u,top:g[c].top+
v,width:g[c].width,height:g[c].height})}}for(var a=d.getElementsByTagName("a"),e={left:0,top:0,width:window.innerWidth,height:window.innerHeight},h=0;h<a.length;++h){var f=a[h],q=!fNative&&b(f);if(rectsIntersected(f.getBoundingClientRect(),e)&&(q||b(f))&&(q=[],n(f,q),0!==q.length)){var t=f.getAttribute("__fireshotLinkId");t?t=parseInt(t):(t=this.collectedLinks.length,f.setAttribute("__fireshotLinkId",t));this.collectedLinks[t]={e:f,r:q}}}},getLinks:function(b,n){var a=b.crop?b.cropRight-b.cropLeft:
b.width,e=b.crop?b.cropBottom-b.cropTop:b.height;b.links=[];for(var h=0;h<this.collectedLinks.length;++h){var f=this.collectedLinks[h],q=this.collectedLinks[h].e;if(!q.getAttribute("__fireshotHiddenLink")){for(var t=[],c=0;c<f.r.length;++c){var p=f.r[c].left-n.x,v=f.r[c].top-n.y,g=f.r[c].width,u=f.r[c].height;p>=a||v>=e||(0>p&&(g+=p,p=0),0>v&&(u+=v,v=0),p+g>a&&(g=a-p),v+u>e&&(u=e-v),0<g&&0<u&&t.push([Math.round(p*b.ratioW),Math.round(v*b.ratioH),Math.round(g*b.ratioW),Math.round(u*b.ratioH)]))}0<
t.length&&b.links.push({a:q.href,r:t,h:""})}}getConsolePtr()("links filtered: "+(this.collectedLinks.length-b.links.length));getConsolePtr()("links added: "+b.links.length)},checkClickableLinks:function(){for(var b,n,a=l.scrollLeft,e=l.scrollTop,h=0;h<this.collectedLinks.length;++h)if(!this.collectedLinks[h].p){b=this.collectedLinks[h].r[0].left-a;n=this.collectedLinks[h].r[0].top-e;0>b&&(b+=this.collectedLinks[h].r[0].width);0>n&&(n+=this.collectedLinks[h].r[0].height);var f;0<=n&&n<=window.innerHeight&&
0<=b&&b<=window.innerWidth&&((f=document.elementFromPoint(Math.round(b+.5),Math.round(n+.5)))===this.collectedLinks[h].e||f&&this.collectedLinks[h].e.contains(f)||this.collectedLinks[h].e.setAttribute("__fireshotHiddenLink",1))}},clearAttributes:function(){for(var b=d.getElementsByTagName("a"),n=0;n<b.length;++n)b[n].removeAttribute("__fireshotHiddenLink"),b[n].removeAttribute("__fireshotLinkId")}}}
function TextGrabber(d){function k(a,e){function h(p){function v(g,u){function x(C,z,G,F){var B=new Range;B.setStart(p,C);B.setEnd(p,z);C=B.getClientRects();z=[];if(F)for(B=0;B<C.length;++B){var E=m(C[B],F);if(0<E.width&&0<E.height){z.push(E);break}}else z=C;0<z.length&&f.push({t:G,r:[Math.floor(z[0].left),Math.floor(z[0].top),Math.ceil(z[0].width),Math.ceil(z[0].height)]})}var w=g,A=p.textContent;if("undefined"!==typeof p.fsOverflowRect)var D=p.fsOverflowRect;for(;w<g+u;){if(""===A[w].trim()){if(void 0!==
y){x(y,w,A.substr(y,w-y),D);var y=void 0}}else void 0===y&&(y=w);++w}void 0!==y&&x(y,g+u,A.substr(y,u-(y-g)),D)}(function(){var g=new Range,u=[],x=p.textContent.length;g.setStart(p,0);g.setEnd(p,x);g=g.getClientRects();if(1===g.length)return[{o:0,l:x}];var w=0,A=1,D=g.length;g=new Range;for(g.setStart(p,w);1<D&&A<x;){g.setEnd(p,A+1);var y=g.getClientRects();1<y.length&&y[0].y!=y[y.length-1].y&&(u.push({o:w,l:A-w}),w=A,g.setStart(p,w),--D);++A}u.push({o:w,l:x-w});return u})().forEach(function(g){return v(g.o,
g.l)})}for(var f=[],q=document.createTreeWalker(a,NodeFilter.SHOW_TEXT,null,!1);a=q.nextNode();)if(a.parentNode&&a.parentNode.getBoundingClientRect){var t=a.parentNode.getBoundingClientRect();if(t&&2<t.width&&2<t.height&&""!==a.textContent.trim()&&(!e||r(e,t))){t=document.defaultView.getComputedStyle(a.parentNode,"");if("rect"===t.clip.substr(0,4)&&"absolute"===t.position){var c=fsRect().fromCSSClip(t.clip);if(4>c.width||4>c.height)continue}"hidden"!==t.visibility&&"none"!==t.display&&"0"!==t.opacity&&
h(a)}}return f}function l(a){for(var e=[],h=document.createTreeWalker(a,NodeFilter.SHOW_ELEMENT,null,!1);a=h.nextNode();)if(a.getBoundingClientRect){var f;(f=!a.childElementCount||"HTML"===a.tagName||"BODY"===a.tagName)||(f=document.defaultView.getComputedStyle(a,""),f=!(f&&"none"!==f.getPropertyValue("display")&&("hidden"===f.getPropertyValue("overflow")||"hidden"===f.getPropertyValue("overflow-y")||"auto"===f.getPropertyValue("overflow-y")||"scroll"==f.getPropertyValue("overflow-y")||"hidden"===
f.getPropertyValue("overflow-x")||"auto"===f.getPropertyValue("overflow-x")||"scroll"==f.getPropertyValue("overflow-x"))));f||e.push(a)}return e}function r(a,e){return a.left<e.left+e.width&&e.left<a.left+a.width&&a.top<e.top+e.height&&e.top<a.top+a.height}function m(a,e){if(r(a,e)){var h=Math.max(a.left,e.left),f=Math.max(a.top,e.top);return new fsRect(h,f,Math.min(a.left+a.width,e.left+e.width)-h,Math.min(a.top+a.height,e.top+e.height)-f)}return new fsRect(0,0,0,0)}function b(a){for(var e=[],h=
0;h<a.length;++h){var f=a[h].getBoundingClientRect();var q=document.defaultView.getComputedStyle(a[h],"");walk=document.createTreeWalker(a[h],NodeFilter.SHOW_TEXT,null,!1);"inline"!==q.display&&(f.width=Math.min(f.width,a[h].clientWidth),f.height=Math.min(f.height,a[h].clientHeight));for(;q=walk.nextNode();)q.parentNode&&q.parentNode.getClientRects&&""!==q.textContent.trim()&&("undefined"!==typeof q.fsOverflowRect?q.fsOverflowRect=m(q.fsOverflowRect,f):(q.fsOverflowRect=f,e.push(q)))}return e}function n(){for(var a,
e=document.createTreeWalker(d,NodeFilter.SHOW_TEXT,null,!1);a=e.nextNode();)"undefined"!==typeof a.fsOverflowRect&&delete a.fsOverflowRect}return{doTests:function(){var a=document.createElement("canvas");a.id="helperCanvas";a.width=document.scrollingElement.scrollWidth-2;a.height=document.scrollingElement.scrollHeight-2;a.style.zIndex=2147483647;a.style.position="absolute";a.style.border="1px solid";a.style.left=0;a.style.top=0;a.style.pointerEvents="none";document.getElementsByTagName("body")[0].prepend(a);
a.getContext("2d");a=performance.now();var e=this.getElements({x:0,y:0},1,1,!1);console.log("Items in array a: "+e.length);console.log("JSON size: "+JSON.stringify(e).length);console.log("Time: "+Math.round(performance.now()-a)+"ms");console.log(e);n();return e},getElements:function(a,e,h,f){b(l(d));f=k(d,f);0==a.x&&0==a.y&&1==e&&1==h||f.forEach(function(q){q.r[0]=Math.round((q.r[0]-a.x)*e);q.r[1]=Math.round((q.r[1]-a.y)*h);q.r[2]=Math.round(q.r[2]*e);q.r[3]=Math.round(q.r[3]*h)});n();return f}}}
;
