/*
 FireShot - Webpage Screenshots and Annotations
 Copyright (C) 2007-2021 Evgeny Suslikov (evgeny@suslikov.ru)
*/
var backgroundPage,fLite,FireShotSettings={loadSettings:function(){$("#edtDefaultFolder").val(backgroundPage.getOption(cDefaultFolderPref,cDefaultFolderValue));$("#chkOpenFolder").prop("checked","true"===backgroundPage.getOption(cOpenFolderAterSavingPref,"false"));$("#chkDoNotShowSaveAsDialog").prop("checked","true"===backgroundPage.getOption(cNoFilenamePromptPref,"false"));$("#chkCloseTab").prop("checked","true"===backgroundPage.getOption(cCloseTabAfterSaving,"false"));$("#edtFilenameTemplate").val(backgroundPage.getOption(cTemplatePref,
cDefaultTemplate));$("#edtTemplateNumber").val(backgroundPage.getOption(cTemplateNumberPref,1));$("#chkTemplateNumberPad").prop("checked","true"===backgroundPage.getOption(cTemplateNumberPadCheckPref,"true"));$("#edtTemplateNumberPad").val(backgroundPage.getOption(cTemplateNumberPadValuePref,3));$("#edtPageScrollingSpeed").val(backgroundPage.getOption(cPageScrollingSpeedPref,100));var a="png"===backgroundPage.getOption(cDefaultImageFormatPref,"png");$("#radImagePNG").prop("checked",a);$("#radImageJPG").prop("checked",
!a);$("#edtTemplateFilenameMaxLen").val(backgroundPage.getOption(cTemplateFilenameMaxLen,100));$("#chkContextMenuIntegration").prop("checked","true"===backgroundPage.getOption(cContextMenuIntegrationPref,"true"));$("#chkAPI").prop("checked","true"===backgroundPage.getOption(cAPISupport,"false"));fLite||$("#chkAllowInfiniteScrolling").prop("checked","true"===backgroundPage.getOption(cAllowInfiniteScrolling,"true"))},saveSettings:function(a){backgroundPage.setOption(cTemplatePref,$("#edtFilenameTemplate").val());
backgroundPage.setOption(cTemplateNumberPref,Math.max(1,parseInt($("#edtTemplateNumber").val())));backgroundPage.setOption(cTemplateNumberPadCheckPref,$("#chkTemplateNumberPad").prop("checked"));backgroundPage.setOption(cTemplateNumberPadValuePref,Math.max(0,parseInt($("#edtTemplateNumberPad").val())));backgroundPage.setOption(cDefaultImageFormatPref,$("#radImagePNG").prop("checked")?"png":"jpg");backgroundPage.setOption(cTemplateFilenameMaxLen,Math.max(10,parseInt($("#edtTemplateFilenameMaxLen").val())));
backgroundPage.setOption(cPageScrollingSpeedPref,Math.min(100,Math.max(1,parseInt($("#edtPageScrollingSpeed").val())||100)));backgroundPage.setOption(cDefaultFolderPref,$("#edtDefaultFolder").val());backgroundPage.setOption(cNoFilenamePromptPref,$("#chkDoNotShowSaveAsDialog").prop("checked"));backgroundPage.setOption(cOpenFolderAterSavingPref,$("#chkOpenFolder").prop("checked"));backgroundPage.setOption(cCloseTabAfterSaving,$("#chkCloseTab").prop("checked"));backgroundPage.setOption(cContextMenuIntegrationPref,
$("#chkContextMenuIntegration").prop("checked"));fLite||backgroundPage.setOption(cAllowInfiniteScrolling,$("#chkAllowInfiniteScrolling").prop("checked"));backgroundPage.updateContextMenu();$("#chkAPI").prop("checked")?addTabsPermission(function(){enableAPI(!0);a&&a()},function(){alert("WARNING: FireShot API is NOT enabled.");enableAPI(!1);$("#chkAPI").prop("checked",!1);a&&a()}):(enableAPI(!1),a&&a())},processHotkey:function(a,b){b.preventDefault();b.stopPropagation();b=getShortcut(b);""!==b&&a.val(b)}};
document.addEventListener("DOMContentLoaded",function(){function a(){var c=/(:)|(\.\.(\\|\/))/.test($("#edtDefaultFolder").val());document.getElementById("spnComment").style.color=c?"#f00":"#666"}function b(){$("#btnLicenseInfo").click(function(){backgroundPage.enterLicense()});$("#btnCapSettings").click(function(){backgroundPage.openCaptureSettings()});$("#btnGeneralOptions").click(function(){backgroundPage.openSettings()});$("#btnApply").click(function(){FireShotSettings.saveSettings()});$("#btnSave").click(function(){FireShotSettings.saveSettings(function(){window.close()})});
$("#btnTemplateSettings").click(function(){$(this).toggle();$("#divTemplateSettings").toggle()});$("#btnTemplateSettingsHide").click(function(){$("#btnTemplateSettings").toggle();$("#divTemplateSettings").toggle()});$("#btnAdvancedFunctions, #lnkActivatePro").click(function(){backgroundPage.installNative()});$("#btnConfigureHotkeys").click(function(){backgroundPage.openURL(isEdge()?"edge://extensions/shortcuts":"chrome://extensions/configureCommands")});$("#edtDefaultFolder").change(a);$("#edtDefaultFolder").keydown(function(){setTimeout(a,
100)})}try{i18nPrepare()}catch(c){logError(c.message)}chrome.runtime.getBackgroundPage(function(c){if(c){backgroundPage=c;fLite=!backgroundPage.isNativeSupported();b();c=isSafari();var d=isFirefox();$(".native").toggle(!fLite);$(".lite").toggle(fLite);$("#fsPro").toggle(fLite&&isWindows());$("[rel='hiddenInSafari']").toggle(!c);$("[rel='shownInFirefox']").toggle(d);$("[rel='hiddenInFirefox']").toggle(!d);"true"===backgroundPage.getOption(cRegisteredPref)&&$("#trLicensingInfo").hide();"hpbicldbpgipcloiojdbchegbbjiobbm"==
extensionId&&$("#trFSAPI").hide();fLite&&($("#chkAllowInfiniteScrolling").prop("disabled",!0),$("#chkAllowInfiniteScrolling").prop("checked",!1));FireShotSettings.loadSettings();a()}})});
